In [1]:
pip install rugbypy

Requirement already satisfied: rugbypy in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (3.0.0)
Requirement already satisfied: fastcore in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from rugbypy) (2.2.33)
Requirement already satisfied: pandas==2.3.3 in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from rugbypy) (2.3.3)
Requirement already satisfied: pyarrow==19.0.0 in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from rugbypy) (19.0.0)
Requirement already satisfied: requests in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from rugbypy) (2.34.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from pandas==2.3.3->rugbypy) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\mey28936\AppData\Local\Programs\Positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from pandas==2.3.3->rugbypy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from pandas==2.3.3->rugbypy) (2026.5)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from pandas==2.3.3->rugbypy) (2026.5)
Requirement already satisfied: six>=1.5 in c:\Users\mey28936\AppData\Local\Programs\Positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from python-dateutil>=2.8.2->pandas==2.3.3->rugbypy) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from requests->rugbypy) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from requests->rugbypy) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from requests->rugbypy) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from requests->rugbypy) (2026.10.18)
Note: you may need to restart the kernel to use updated packages.

In [2]:
from rugbypy.match import *
from rugbypy.competition import *
from rugbypy.team import *
from rugbypy.venue import *
from rugbypy.player import *

In [3]:
import pandas as pd
import polars as pl
import matplotlib.pyplot as plt
import numpy as np

In [4]:
test_nations = pd.read_excel("test_nations.xlsx")

test_nations

     team_id     team_name
0   67d88578        France
1   094dae60         Wales
2   d0cffe5e         Italy
3   4409215c      Scotland
4   f60f757d       England
5   165b36e5       Ireland
6   9b93d911  South Africa
7   11392c0c     Argentina
8   b904fef9     Australia
9   d75e45cc   New Zealand
10  f97333f3         Japan
11  3a1983b3          Fiji

In [5]:
all_team_stats = pd.DataFrame()
team_ids = test_nations['team_id']

for id in team_ids:
    all_team_stats = pd.concat([all_team_stats, fetch_team_stats(team_id=id)], ignore_index=True)

Fetching all team stats for team_id: 67d88578...
Fetching all team stats for team_id: 094dae60...
Fetching all team stats for team_id: d0cffe5e...
Fetching all team stats for team_id: 4409215c...
Fetching all team stats for team_id: f60f757d...
Fetching all team stats for team_id: 165b36e5...
Fetching all team stats for team_id: 9b93d911...
Fetching all team stats for team_id: 11392c0c...
Fetching all team stats for team_id: b904fef9...
Fetching all team stats for team_id: d75e45cc...
Fetching all team stats for team_id: f97333f3...
Fetching all team stats for team_id: 3a1983b3...

In [6]:
all_team_stats

,team_id,team,game_date,team_vs,team_vs_id,match_id,players,score,team_vs_score,22m_entries,...,offload,pc_possession_first,pc_possession_second,pc_territory_first,pc_territory_second,rucks_total,runs,scrums_total,total_free_kicks_conceded,turnover_knock_on
0,67d88578,France,20220206,Italy,d0cffe5e,4a49c716,"[0042c61a, 01b8ac07, 0e930fa8, 1d490b9e, 252ec...",NaN,NaN,NaN,...,9.0,0.62,0.54,0.66,0.64,96.0,124.0,5.0,0.0,7.0
1,67d88578,France,20220212,Ireland,165b36e5,71ccf2fb,"[0042c61a, 01b8ac07, 065c26ea, 0e930fa8, 1d490...",NaN,NaN,NaN,...,8.0,0.52,0.43,0.55,0.48,83.0,101.0,5.0,1.0,7.0
2,67d88578,France,20220226,Scotland,4409215c,eb863c39,"[0042c61a, 01b8ac07, 065c26ea, 0e930fa8, 252ec...",NaN,NaN,NaN,...,10.0,0.45,0.39,0.39,0.61,41.0,75.0,9.0,1.0,6.0
3,67d88578,France,20220311,Wales,094dae60,6b6585fc,"[065c26ea, 0e930fa8, 1d490b9e, 252ecbf2, 26273...",NaN,NaN,NaN,...,10.0,0.53,0.41,0.55,0.33,69.0,98.0,6.0,1.0,9.0
4,67d88578,France,20220319,England,f60f757d,cc3c0a71,"[0042c61a, 065c26ea, 0e930fa8, 1d490b9e, 252ec...",NaN,NaN,NaN,...,13.0,0.51,0.39,0.60,0.27,71.0,98.0,9.0,0.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,3a1983b3,Fiji,20241123,Ireland,165b36e5,8923cd55,"[0147de23, 117cc1c5, 18853774, 1f45395b, 1ff21...",17.0,52.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
479,3a1983b3,Fiji,20250830,Tonga,be110f80,b901c3ad,"[0147de23, 07539167, 117cc1c5, 18b260a8, 1f453...",32.0,10.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
480,3a1983b3,Fiji,20250906,Samoa,23778ceb,aa4c09a1,"[0147de23, 07539167, 112c163a, 117cc1c5, 18b26...",29.0,15.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
481,3a1983b3,Fiji,20250915,Canada,1039f7c4,55e97718,"[0147de23, 112c163a, 18b260a8, 1f45395b, 2296d...",10.0,63.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
482,3a1983b3,Fiji,20250921,Japan,f97333f3,19a16e21,"[0147de23, 112c163a, 117cc1c5, 1f45395b, 1ff21...",27.0,33.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
all_players = all_team_stats[['game_date', 'players']]

all_players

    game_date                                            players
0    20220206  [0042c61a, 01b8ac07, 0e930fa8, 1d490b9e, 252ec...
1    20220212  [0042c61a, 01b8ac07, 065c26ea, 0e930fa8, 1d490...
2    20220226  [0042c61a, 01b8ac07, 065c26ea, 0e930fa8, 252ec...
3    20220311  [065c26ea, 0e930fa8, 1d490b9e, 252ecbf2, 26273...
4    20220319  [0042c61a, 065c26ea, 0e930fa8, 1d490b9e, 252ec...
..        ...                                                ...
478  20241123  [0147de23, 117cc1c5, 18853774, 1f45395b, 1ff21...
479  20250830  [0147de23, 07539167, 117cc1c5, 18b260a8, 1f453...
480  20250906  [0147de23, 07539167, 112c163a, 117cc1c5, 18b26...
481  20250915  [0147de23, 112c163a, 18b260a8, 1f45395b, 2296d...
482  20250921  [0147de23, 112c163a, 117cc1c5, 1f45395b, 1ff21...

[483 rows x 2 columns]

In [8]:
all_players = all_players[all_players['players'].str.len() > 1]


all_players

    game_date                                            players
0    20220206  [0042c61a, 01b8ac07, 0e930fa8, 1d490b9e, 252ec...
1    20220212  [0042c61a, 01b8ac07, 065c26ea, 0e930fa8, 1d490...
2    20220226  [0042c61a, 01b8ac07, 065c26ea, 0e930fa8, 252ec...
3    20220311  [065c26ea, 0e930fa8, 1d490b9e, 252ecbf2, 26273...
4    20220319  [0042c61a, 065c26ea, 0e930fa8, 1d490b9e, 252ec...
..        ...                                                ...
478  20241123  [0147de23, 117cc1c5, 18853774, 1f45395b, 1ff21...
479  20250830  [0147de23, 07539167, 117cc1c5, 18b260a8, 1f453...
480  20250906  [0147de23, 07539167, 112c163a, 117cc1c5, 18b26...
481  20250915  [0147de23, 112c163a, 18b260a8, 1f45395b, 2296d...
482  20250921  [0147de23, 112c163a, 117cc1c5, 1f45395b, 1ff21...

[307 rows x 2 columns]

In [9]:
player_stats = pd.DataFrame()
dfs = []

for date, ids in zip(all_players['game_date'], all_players['players']):
    for id in ids:
        dfs.append(
            fetch_player_stats(
                player_id = id,
                date = date
            )
        )

player_stats = pd.concat(dfs, ignore_index=True)

Fetching player stats for player_id: 0042c61a on date: 20220206...
Fetching player stats for player_id: 01b8ac07 on date: 20220206...
Fetching player stats for player_id: 0e930fa8 on date: 20220206...
Fetching player stats for player_id: 1d490b9e on date: 20220206...
Fetching player stats for player_id: 252ecbf2 on date: 20220206...
Fetching player stats for player_id: 26273081 on date: 20220206...
Fetching player stats for player_id: 2c39da94 on date: 20220206...
Fetching player stats for player_id: 3c388133 on date: 20220206...
Fetching player stats for player_id: 64b1dbeb on date: 20220206...
Fetching player stats for player_id: 714b76d3 on date: 20220206...
Fetching player stats for player_id: 71f25ae6 on date: 20220206...
Fetching player stats for player_id: 7a9d8e51 on date: 20220206...
Fetching player stats for player_id: 8ba10277 on date: 20220206...
Fetching player stats for player_id: 8d2ac40f on date: 20220206...
Fetching player stats for player_id: 991bb389 on date: 20220206...
Fetching player stats for player_id: 9b5b5a3c on date: 20220206...
Fetching player stats for player_id: be569f12 on date: 20220206...
Fetching player stats for player_id: be6163d9 on date: 20220206...
Fetching player stats for player_id: c3958443 on date: 20220206...
Fetching player stats for player_id: d30fed66 on date: 20220206...
Fetching player stats for player_id: d581f227 on date: 20220206...
Fetching player stats for player_id: dee2466d on date: 20220206...
Fetching player stats for player_id: e8718ec4 on date: 20220206...
Fetching player stats for player_id: 0042c61a on date: 20220212...
Fetching player stats for player_id: 01b8ac07 on date: 20220212...
Fetching player stats for player_id: 065c26ea on date: 20220212...
Fetching player stats for player_id: 0e930fa8 on date: 20220212...
Fetching player stats for player_id: 1d490b9e on date: 20220212...
Fetching player stats for player_id: 252ecbf2 on date: 20220212...
Fetching player stats for player_id: 2c39da94 on date: 20220212...
Fetching player stats for player_id: 3c388133 on date: 20220212...
Fetching player stats for player_id: 64b1dbeb on date: 20220212...
Fetching player stats for player_id: 714b76d3 on date: 20220212...
Fetching player stats for player_id: 71f25ae6 on date: 20220212...
Fetching player stats for player_id: 7a9d8e51 on date: 20220212...
Fetching player stats for player_id: 8ba10277 on date: 20220212...
Fetching player stats for player_id: 8d2ac40f on date: 20220212...
Fetching player stats for player_id: 991bb389 on date: 20220212...
Fetching player stats for player_id: 9b5b5a3c on date: 20220212...
Fetching player stats for player_id: be569f12 on date: 20220212...
Fetching player stats for player_id: be6163d9 on date: 20220212...
Fetching player stats for player_id: c3958443 on date: 20220212...
Fetching player stats for player_id: d30fed66 on date: 20220212...
Fetching player stats for player_id: d581f227 on date: 20220212...
Fetching player stats for player_id: dee2466d on date: 20220212...
Fetching player stats for player_id: e8718ec4 on date: 20220212...
Fetching player stats for player_id: 0042c61a on date: 20220226...
Fetching player stats for player_id: 01b8ac07 on date: 20220226...
Fetching player stats for player_id: 065c26ea on date: 20220226...
Fetching player stats for player_id: 0e930fa8 on date: 20220226...
Fetching player stats for player_id: 252ecbf2 on date: 20220226...
Fetching player stats for player_id: 26273081 on date: 20220226...
Fetching player stats for player_id: 2c39da94 on date: 20220226...
Fetching player stats for player_id: 3c388133 on date: 20220226...
Fetching player stats for player_id: 64b1dbeb on date: 20220226...
Fetching player stats for player_id: 714b76d3 on date: 20220226...
Fetching player stats for player_id: 71f25ae6 on date: 20220226...
Fetching player stats for player_id: 7a9d8e51 on date: 20220226...
Fetching player stats for player_id: 8ba10277 on date: 20220226...
Fetching player stats for player_id: 8d2ac40f on date: 20220226...
Fetching player stats for player_id: 991bb389 on date: 20220226...
Fetching player stats for player_id: 9b5b5a3c on date: 20220226...
Fetching player stats for player_id: be569f12 on date: 20220226...
Fetching player stats for player_id: be6163d9 on date: 20220226...
Fetching player stats for player_id: c3958443 on date: 20220226...
Fetching player stats for player_id: d30fed66 on date: 20220226...
Fetching player stats for player_id: d581f227 on date: 20220226...
Fetching player stats for player_id: dee2466d on date: 20220226...
Fetching player stats for player_id: e8718ec4 on date: 20220226...
Fetching player stats for player_id: 065c26ea on date: 20220311...
Fetching player stats for player_id: 0e930fa8 on date: 20220311...
Fetching player stats for player_id: 1d490b9e on date: 20220311...
Fetching player stats for player_id: 252ecbf2 on date: 20220311...
Fetching player stats for player_id: 26273081 on date: 20220311...
Fetching player stats for player_id: 2c39da94 on date: 20220311...
Fetching player stats for player_id: 3c388133 on date: 20220311...
Fetching player stats for player_id: 6440018e on date: 20220311...
Fetching player stats for player_id: 64b1dbeb on date: 20220311...
Fetching player stats for player_id: 714b76d3 on date: 20220311...
Fetching player stats for player_id: 71f25ae6 on date: 20220311...
Fetching player stats for player_id: 7a9d8e51 on date: 20220311...
Fetching player stats for player_id: 8521521c on date: 20220311...
Fetching player stats for player_id: 8ba10277 on date: 20220311...
Fetching player stats for player_id: 8d2ac40f on date: 20220311...
Fetching player stats for player_id: 991bb389 on date: 20220311...
Fetching player stats for player_id: 9b5b5a3c on date: 20220311...
Fetching player stats for player_id: be569f12 on date: 20220311...
Fetching player stats for player_id: be6163d9 on date: 20220311...
Fetching player stats for player_id: c3958443 on date: 20220311...
Fetching player stats for player_id: d581f227 on date: 20220311...
Fetching player stats for player_id: dee2466d on date: 20220311...
Fetching player stats for player_id: e8718ec4 on date: 20220311...
Fetching player stats for player_id: 0042c61a on date: 20220319...
Fetching player stats for player_id: 065c26ea on date: 20220319...
Fetching player stats for player_id: 0e930fa8 on date: 20220319...
Fetching player stats for player_id: 1d490b9e on date: 20220319...
Fetching player stats for player_id: 252ecbf2 on date: 20220319...
Fetching player stats for player_id: 26273081 on date: 20220319...
Fetching player stats for player_id: 2c39da94 on date: 20220319...
Fetching player stats for player_id: 3c388133 on date: 20220319...
Fetching player stats for player_id: 64b1dbeb on date: 20220319...
Fetching player stats for player_id: 714b76d3 on date: 20220319...
Fetching player stats for player_id: 71f25ae6 on date: 20220319...
Fetching player stats for player_id: 7a9d8e51 on date: 20220319...
Fetching player stats for player_id: 8521521c on date: 20220319...
Fetching player stats for player_id: 8ba10277 on date: 20220319...
Fetching player stats for player_id: 8d2ac40f on date: 20220319...
Fetching player stats for player_id: 991bb389 on date: 20220319...
Fetching player stats for player_id: 9b5b5a3c on date: 20220319...
Fetching player stats for player_id: be569f12 on date: 20220319...
Fetching player stats for player_id: c3958443 on date: 20220319...
Fetching player stats for player_id: d30fed66 on date: 20220319...
Fetching player stats for player_id: d581f227 on date: 20220319...
Fetching player stats for player_id: dee2466d on date: 20220319...
Fetching player stats for player_id: e8718ec4 on date: 20220319...
Fetching player stats for player_id: 0042c61a on date: 20230205...
Fetching player stats for player_id: 03b2a75c on date: 20230205...
Fetching player stats for player_id: 065c26ea on date: 20230205...
Fetching player stats for player_id: 083d28be on date: 20230205...
Fetching player stats for player_id: 0e930fa8 on date: 20230205...
Fetching player stats for player_id: 1d66f423 on date: 20230205...
Fetching player stats for player_id: 25974b3c on date: 20230205...
Fetching player stats for player_id: 30b79e7c on date: 20230205...
Fetching player stats for player_id: 3c7620ca on date: 20230205...
Fetching player stats for player_id: 497e679e on date: 20230205...
Fetching player stats for player_id: 64b1dbeb on date: 20230205...
Fetching player stats for player_id: 714b76d3 on date: 20230205...
Fetching player stats for player_id: 71f25ae6 on date: 20230205...
Fetching player stats for player_id: 7a9d8e51 on date: 20230205...
Fetching player stats for player_id: 8d2ac40f on date: 20230205...
Fetching player stats for player_id: 991bb389 on date: 20230205...
Fetching player stats for player_id: b05a23f1 on date: 20230205...
Fetching player stats for player_id: b4305299 on date: 20230205...
Fetching player stats for player_id: be569f12 on date: 20230205...
Fetching player stats for player_id: be6163d9 on date: 20230205...
Fetching player stats for player_id: d30fed66 on date: 20230205...
Fetching player stats for player_id: d581f227 on date: 20230205...
Fetching player stats for player_id: dee2466d on date: 20230205...
Fetching player stats for player_id: 0042c61a on date: 20230211...
Fetching player stats for player_id: 065c26ea on date: 20230211...
Fetching player stats for player_id: 083d28be on date: 20230211...
Fetching player stats for player_id: 0e930fa8 on date: 20230211...
Fetching player stats for player_id: 1d66f423 on date: 20230211...
Fetching player stats for player_id: 25974b3c on date: 20230211...
Fetching player stats for player_id: 2c39da94 on date: 20230211...
Fetching player stats for player_id: 30b79e7c on date: 20230211...
Fetching player stats for player_id: 3c7620ca on date: 20230211...
Fetching player stats for player_id: 497e679e on date: 20230211...
Fetching player stats for player_id: 64b1dbeb on date: 20230211...
Fetching player stats for player_id: 714b76d3 on date: 20230211...
Fetching player stats for player_id: 71f25ae6 on date: 20230211...
Fetching player stats for player_id: 7a9d8e51 on date: 20230211...
Fetching player stats for player_id: 8d2ac40f on date: 20230211...
Fetching player stats for player_id: 991bb389 on date: 20230211...
Fetching player stats for player_id: b05a23f1 on date: 20230211...
Fetching player stats for player_id: be569f12 on date: 20230211...
Fetching player stats for player_id: be6163d9 on date: 20230211...
Fetching player stats for player_id: c5815c3c on date: 20230211...
Fetching player stats for player_id: d30fed66 on date: 20230211...
Fetching player stats for player_id: d581f227 on date: 20230211...
Fetching player stats for player_id: dee2466d on date: 20230211...
Fetching player stats for player_id: 0042c61a on date: 20230226...
Fetching player stats for player_id: 065c26ea on date: 20230226...
Fetching player stats for player_id: 083d28be on date: 20230226...
Fetching player stats for player_id: 0e930fa8 on date: 20230226...
Fetching player stats for player_id: 1d66f423 on date: 20230226...
Fetching player stats for player_id: 25974b3c on date: 20230226...
Fetching player stats for player_id: 2c39da94 on date: 20230226...
Fetching player stats for player_id: 30b79e7c on date: 20230226...
Fetching player stats for player_id: 3c7620ca on date: 20230226...
Fetching player stats for player_id: 497e679e on date: 20230226...
Fetching player stats for player_id: 64b1dbeb on date: 20230226...
Fetching player stats for player_id: 714b76d3 on date: 20230226...
Fetching player stats for player_id: 7a9d8e51 on date: 20230226...
Fetching player stats for player_id: 8521521c on date: 20230226...
Fetching player stats for player_id: 8d2ac40f on date: 20230226...
Fetching player stats for player_id: 991bb389 on date: 20230226...
Fetching player stats for player_id: b05a23f1 on date: 20230226...
Fetching player stats for player_id: be569f12 on date: 20230226...
Fetching player stats for player_id: be6163d9 on date: 20230226...
Fetching player stats for player_id: c5815c3c on date: 20230226...
Fetching player stats for player_id: d30fed66 on date: 20230226...
Fetching player stats for player_id: d581f227 on date: 20230226...
Fetching player stats for player_id: dee2466d on date: 20230226...
Fetching player stats for player_id: 0042c61a on date: 20230311...
Fetching player stats for player_id: 065c26ea on date: 20230311...
Fetching player stats for player_id: 083d28be on date: 20230311...
Fetching player stats for player_id: 0e930fa8 on date: 20230311...
Fetching player stats for player_id: 1d66f423 on date: 20230311...
Fetching player stats for player_id: 25974b3c on date: 20230311...
Fetching player stats for player_id: 26273081 on date: 20230311...
Fetching player stats for player_id: 2c39da94 on date: 20230311...
Fetching player stats for player_id: 30b79e7c on date: 20230311...
Fetching player stats for player_id: 3c388133 on date: 20230311...
Fetching player stats for player_id: 497e679e on date: 20230311...
Fetching player stats for player_id: 64b1dbeb on date: 20230311...
Fetching player stats for player_id: 714b76d3 on date: 20230311...
Fetching player stats for player_id: 7a9d8e51 on date: 20230311...
Fetching player stats for player_id: 991bb389 on date: 20230311...
Fetching player stats for player_id: 9b5b5a3c on date: 20230311...
Fetching player stats for player_id: a5ce7b34 on date: 20230311...
Fetching player stats for player_id: be569f12 on date: 20230311...
Fetching player stats for player_id: be6163d9 on date: 20230311...
Fetching player stats for player_id: c3958443 on date: 20230311...
Fetching player stats for player_id: d30fed66 on date: 20230311...
Fetching player stats for player_id: d581f227 on date: 20230311...
Fetching player stats for player_id: dee2466d on date: 20230311...
Fetching player stats for player_id: 0042c61a on date: 20230318...
Fetching player stats for player_id: 065c26ea on date: 20230318...
Fetching player stats for player_id: 083d28be on date: 20230318...
Fetching player stats for player_id: 0e930fa8 on date: 20230318...
Fetching player stats for player_id: 1d66f423 on date: 20230318...
Fetching player stats for player_id: 25974b3c on date: 20230318...
Fetching player stats for player_id: 26273081 on date: 20230318...
Fetching player stats for player_id: 2c39da94 on date: 20230318...
Fetching player stats for player_id: 30b79e7c on date: 20230318...
Fetching player stats for player_id: 32a43615 on date: 20230318...
Fetching player stats for player_id: 3c388133 on date: 20230318...
Fetching player stats for player_id: 497e679e on date: 20230318...
Fetching player stats for player_id: 714b76d3 on date: 20230318...
Fetching player stats for player_id: 71f25ae6 on date: 20230318...
Fetching player stats for player_id: 7a9d8e51 on date: 20230318...
Fetching player stats for player_id: 991bb389 on date: 20230318...
Fetching player stats for player_id: 9b5b5a3c on date: 20230318...
Fetching player stats for player_id: be569f12 on date: 20230318...
Fetching player stats for player_id: be6163d9 on date: 20230318...
Fetching player stats for player_id: c3958443 on date: 20230318...
Fetching player stats for player_id: d30fed66 on date: 20230318...
Fetching player stats for player_id: d581f227 on date: 20230318...
Fetching player stats for player_id: dee2466d on date: 20230318...
Fetching player stats for player_id: 0042c61a on date: 20240202...
Fetching player stats for player_id: 083d28be on date: 20240202...
Fetching player stats for player_id: 26273081 on date: 20240202...
Fetching player stats for player_id: 2c39da94 on date: 20240202...
Fetching player stats for player_id: 3c388133 on date: 20240202...
Fetching player stats for player_id: 3c7620ca on date: 20240202...
Fetching player stats for player_id: 497e679e on date: 20240202...
Fetching player stats for player_id: 4988ecdd on date: 20240202...
Fetching player stats for player_id: 5662ef22 on date: 20240202...
Fetching player stats for player_id: 64b1dbeb on date: 20240202...
Fetching player stats for player_id: 71f25ae6 on date: 20240202...
Fetching player stats for player_id: 7a9d8e51 on date: 20240202...
Fetching player stats for player_id: 8ba10277 on date: 20240202...
Fetching player stats for player_id: 972ae703 on date: 20240202...
Fetching player stats for player_id: 991bb389 on date: 20240202...
Fetching player stats for player_id: 9b5b5a3c on date: 20240202...
Fetching player stats for player_id: a5ce7b34 on date: 20240202...
Fetching player stats for player_id: b4305299 on date: 20240202...
Fetching player stats for player_id: be569f12 on date: 20240202...
Fetching player stats for player_id: be6163d9 on date: 20240202...
Fetching player stats for player_id: d30fed66 on date: 20240202...
Fetching player stats for player_id: d5784e57 on date: 20240202...
Fetching player stats for player_id: d581f227 on date: 20240202...
Fetching player stats for player_id: dee2466d on date: 20240202...
Fetching player stats for player_id: 0042c61a on date: 20240210...
Fetching player stats for player_id: 26273081 on date: 20240210...
Fetching player stats for player_id: 2c39da94 on date: 20240210...
Fetching player stats for player_id: 3c388133 on date: 20240210...
Fetching player stats for player_id: 3c7620ca on date: 20240210...
Fetching player stats for player_id: 497e679e on date: 20240210...
Fetching player stats for player_id: 4988ecdd on date: 20240210...
Fetching player stats for player_id: 5662ef22 on date: 20240210...
Fetching player stats for player_id: 71f25ae6 on date: 20240210...
Fetching player stats for player_id: 7a9d8e51 on date: 20240210...
Fetching player stats for player_id: 8ba10277 on date: 20240210...
Fetching player stats for player_id: 972ae703 on date: 20240210...
Fetching player stats for player_id: 991bb389 on date: 20240210...
Fetching player stats for player_id: 9b5b5a3c on date: 20240210...
Fetching player stats for player_id: a3d002a3 on date: 20240210...
Fetching player stats for player_id: a5ce7b34 on date: 20240210...
Fetching player stats for player_id: b4305299 on date: 20240210...
Fetching player stats for player_id: be569f12 on date: 20240210...
Fetching player stats for player_id: be6163d9 on date: 20240210...
Fetching player stats for player_id: d5784e57 on date: 20240210...
Fetching player stats for player_id: d581f227 on date: 20240210...
Fetching player stats for player_id: d8fe06bd on date: 20240210...
Fetching player stats for player_id: dee2466d on date: 20240210...
Fetching player stats for player_id: 0042c61a on date: 20240225...
Fetching player stats for player_id: 26273081 on date: 20240225...
Fetching player stats for player_id: 2c39da94 on date: 20240225...
Fetching player stats for player_id: 3c388133 on date: 20240225...
Fetching player stats for player_id: 3c7620ca on date: 20240225...
Fetching player stats for player_id: 497e679e on date: 20240225...
Fetching player stats for player_id: 4988ecdd on date: 20240225...
Fetching player stats for player_id: 5662ef22 on date: 20240225...
Fetching player stats for player_id: 5d5b9668 on date: 20240225...
Fetching player stats for player_id: 6440018e on date: 20240225...
Fetching player stats for player_id: 71f25ae6 on date: 20240225...
Fetching player stats for player_id: 7a9d8e51 on date: 20240225...
Fetching player stats for player_id: 8ba10277 on date: 20240225...
Fetching player stats for player_id: 991bb389 on date: 20240225...
Fetching player stats for player_id: 9b5b5a3c on date: 20240225...
Fetching player stats for player_id: a3d002a3 on date: 20240225...
Fetching player stats for player_id: a5ce7b34 on date: 20240225...
Fetching player stats for player_id: b4305299 on date: 20240225...
Fetching player stats for player_id: be569f12 on date: 20240225...
Fetching player stats for player_id: be6163d9 on date: 20240225...
Fetching player stats for player_id: d30fed66 on date: 20240225...

In [10]:
player_stats

,player_id,name,team,team_id,position,carries,line_breaks,tackles_completed,turnovers_lost,turnovers_won,...,runs,tackles,total_free_kicks_conceded,total_lineouts,turnover_knock_on,turnovers_conceded,player_name,want_team,want_teamvs,minutes_played
0,0042c61a,Damian Penaud,France,67d88578,wing,8.0,2.0,NaN,NaN,NaN,...,8.0,5.0,0.0,0.0,2.0,2.0,None,67d88578,d0cffe5e,NaN
1,01b8ac07,Demba Bamba,France,67d88578,prop,0.0,0.0,NaN,NaN,NaN,...,0.0,3.0,0.0,0.0,1.0,1.0,None,67d88578,d0cffe5e,NaN
2,0e930fa8,Romain Ntamack,France,67d88578,fly_half,0.0,0.0,NaN,NaN,NaN,...,0.0,10.0,0.0,0.0,0.0,0.0,None,67d88578,d0cffe5e,NaN
3,1d490b9e,Gabin Villiere,France,67d88578,wing,13.0,3.0,NaN,NaN,NaN,...,13.0,1.0,0.0,0.0,2.0,3.0,None,67d88578,d0cffe5e,NaN
4,252ecbf2,Jean-Baptiste Gros,France,67d88578,prop,3.0,0.0,NaN,NaN,NaN,...,3.0,5.0,0.0,0.0,0.0,0.0,None,67d88578,d0cffe5e,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6968,d33e6bc6,Taniela Rakuro,Fiji,3a1983b3,left_wing,4.0,1.0,10.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,None,3a1983b3,f97333f3,NaN
6969,d72ddff6,Inia Tabuavou,Fiji,3a1983b3,inside_centre,9.0,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,None,3a1983b3,f97333f3,NaN
6970,d916e47c,Samu Tawake,Fiji,3a1983b3,front_row_sub,4.0,0.0,4.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,None,3a1983b3,f97333f3,NaN
6971,f5452b67,Eroni Mawi,Fiji,3a1983b3,loosehead_prop,3.0,0.0,11.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,None,3a1983b3,f97333f3,NaN
6972,fd05cd82,Mesake Doge,Fiji,3a1983b3,tighthead_prop,3.0,0.0,13.0,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,None,3a1983b3,f97333f3,NaN

In [27]:
## Only including test matches

match_stats = player_stats[player_stats['team_id'].isin(test_nations['team_id'])]

match_stats

,player_id,name,team,team_id,position,carries,line_breaks,tackles_completed,turnovers_lost,turnovers_won,...,runs,tackles,total_free_kicks_conceded,total_lineouts,turnover_knock_on,turnovers_conceded,player_name,want_team,want_teamvs,minutes_played
0,0042c61a,Damian Penaud,France,67d88578,wing,8.0,2.0,NaN,NaN,NaN,...,8.0,5.0,0.0,0.0,2.0,2.0,None,67d88578,d0cffe5e,NaN
1,01b8ac07,Demba Bamba,France,67d88578,prop,0.0,0.0,NaN,NaN,NaN,...,0.0,3.0,0.0,0.0,1.0,1.0,None,67d88578,d0cffe5e,NaN
2,0e930fa8,Romain Ntamack,France,67d88578,fly_half,0.0,0.0,NaN,NaN,NaN,...,0.0,10.0,0.0,0.0,0.0,0.0,None,67d88578,d0cffe5e,NaN
3,1d490b9e,Gabin Villiere,France,67d88578,wing,13.0,3.0,NaN,NaN,NaN,...,13.0,1.0,0.0,0.0,2.0,3.0,None,67d88578,d0cffe5e,NaN
4,252ecbf2,Jean-Baptiste Gros,France,67d88578,prop,3.0,0.0,NaN,NaN,NaN,...,3.0,5.0,0.0,0.0,0.0,0.0,None,67d88578,d0cffe5e,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6968,d33e6bc6,Taniela Rakuro,Fiji,3a1983b3,left_wing,4.0,1.0,10.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,None,3a1983b3,f97333f3,NaN
6969,d72ddff6,Inia Tabuavou,Fiji,3a1983b3,inside_centre,9.0,0.0,2.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,None,3a1983b3,f97333f3,NaN
6970,d916e47c,Samu Tawake,Fiji,3a1983b3,front_row_sub,4.0,0.0,4.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,None,3a1983b3,f97333f3,NaN
6971,f5452b67,Eroni Mawi,Fiji,3a1983b3,loosehead_prop,3.0,0.0,11.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,None,3a1983b3,f97333f3,NaN
6972,fd05cd82,Mesake Doge,Fiji,3a1983b3,tighthead_prop,3.0,0.0,13.0,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,None,3a1983b3,f97333f3,NaN

In [28]:
## Aggregating stats to collect team totals

match_stats = (match_stats.groupby(["team", "match_id"], as_index=False)
      .sum(numeric_only=True)
)

match_stats.head()

,team,match_id,carries,line_breaks,tackles_completed,turnovers_lost,turnovers_won,kicks,passes,metres_carried,...,penalty_goals,points,rucks_won,runs,tackles,total_free_kicks_conceded,total_lineouts,turnover_knock_on,turnovers_conceded,minutes_played
0,Argentina,0381b537,113.0,3.0,169.0,13.0,1.0,27.0,109.0,367.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Argentina,0c15dfc8,117.0,4.0,95.0,9.0,4.0,16.0,153.0,312.0,...,2.0,13.0,80.0,117.0,95.0,1.0,13.0,6.0,9.0,0.0
2,Argentina,20335bcb,92.0,3.0,92.0,12.0,4.0,22.0,112.0,321.0,...,0.0,21.0,67.0,92.0,92.0,0.0,20.0,3.0,12.0,0.0
3,Argentina,2864ca3c,97.0,7.0,130.0,11.0,6.0,29.0,123.0,393.0,...,1.0,48.0,71.0,97.0,130.0,0.0,14.0,8.0,11.0,0.0
4,Argentina,337dd942,129.0,6.0,188.0,16.0,2.0,38.0,189.0,189.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
match_stats.to_excel("aggregated_stats.xlsx", index=False)