In [1]:
pip install rugbypy

Requirement already satisfied: rugbypy in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (3.0.0)
Requirement already satisfied: fastcore in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from rugbypy) (2.2.33)
Requirement already satisfied: pandas==2.3.3 in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from rugbypy) (2.3.3)
Requirement already satisfied: pyarrow==19.0.0 in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from rugbypy) (19.0.0)
Requirement already satisfied: requests in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from rugbypy) (2.34.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from pandas==2.3.3->rugbypy) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\mey28936\AppData\Local\Programs\Positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from pandas==2.3.3->rugbypy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from pandas==2.3.3->rugbypy) (2026.5)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from pandas==2.3.3->rugbypy) (2026.5)
Requirement already satisfied: six>=1.5 in c:\Users\mey28936\AppData\Local\Programs\Positron\resources\app\extensions\positron-python\python_files\lib\ipykernel\py3 (from python-dateutil>=2.8.2->pandas==2.3.3->rugbypy) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from requests->rugbypy) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from requests->rugbypy) (3.20)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from requests->rugbypy) (2.8.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\mey28936\.virtualenvs\positron\Lib\site-packages (from requests->rugbypy) (2026.10.18)
Note: you may need to restart the kernel to use updated packages.

In [2]:
from rugbypy.match import *
from rugbypy.competition import *
from rugbypy.team import *
from rugbypy.venue import *
from rugbypy.player import *

In [ ]:
import pandas as pd
import polars as pl
import matplotlib.pyplot as plt
import numpy as np

In [6]:
test_nations = pd.read_excel("test_nations.xlsx")

test_nations

     team_id     team_name
0   67d88578        France
1   094dae60         Wales
2   d0cffe5e         Italy
3   4409215c      Scotland
4   f60f757d       England
5   165b36e5       Ireland
6   9b93d911  South Africa
7   11392c0c     Argentina
8   b904fef9     Australia
9   d75e45cc   New Zealand
10  f97333f3         Japan
11  3a1983b3          Fiji

In [9]:
all_team_stats = pd.DataFrame()
team_ids = test_nations['team_id']

for id in team_ids:
    all_team_stats = pd.concat([all_team_stats, fetch_team_stats(team_id=id)], ignore_index=True)

Fetching all team stats for team_id: 67d88578...
Fetching all team stats for team_id: 094dae60...
Fetching all team stats for team_id: d0cffe5e...
Fetching all team stats for team_id: 4409215c...
Fetching all team stats for team_id: f60f757d...
Fetching all team stats for team_id: 165b36e5...
Fetching all team stats for team_id: 9b93d911...
Fetching all team stats for team_id: 11392c0c...
Fetching all team stats for team_id: b904fef9...
Fetching all team stats for team_id: d75e45cc...
Fetching all team stats for team_id: f97333f3...
Fetching all team stats for team_id: 3a1983b3...

In [12]:
all_team_stats

,team_id,team,game_date,team_vs,team_vs_id,match_id,players,score,team_vs_score,22m_entries,...,offload,pc_possession_first,pc_possession_second,pc_territory_first,pc_territory_second,rucks_total,runs,scrums_total,total_free_kicks_conceded,turnover_knock_on
0,67d88578,France,20220206,Italy,d0cffe5e,4a49c716,"[0042c61a, 01b8ac07, 0e930fa8, 1d490b9e, 252ec...",NaN,NaN,NaN,...,9.0,0.62,0.54,0.66,0.64,96.0,124.0,5.0,0.0,7.0
1,67d88578,France,20220212,Ireland,165b36e5,71ccf2fb,"[0042c61a, 01b8ac07, 065c26ea, 0e930fa8, 1d490...",NaN,NaN,NaN,...,8.0,0.52,0.43,0.55,0.48,83.0,101.0,5.0,1.0,7.0
2,67d88578,France,20220226,Scotland,4409215c,eb863c39,"[0042c61a, 01b8ac07, 065c26ea, 0e930fa8, 252ec...",NaN,NaN,NaN,...,10.0,0.45,0.39,0.39,0.61,41.0,75.0,9.0,1.0,6.0
3,67d88578,France,20220311,Wales,094dae60,6b6585fc,"[065c26ea, 0e930fa8, 1d490b9e, 252ecbf2, 26273...",NaN,NaN,NaN,...,10.0,0.53,0.41,0.55,0.33,69.0,98.0,6.0,1.0,9.0
4,67d88578,France,20220319,England,f60f757d,cc3c0a71,"[0042c61a, 065c26ea, 0e930fa8, 1d490b9e, 252ec...",NaN,NaN,NaN,...,13.0,0.51,0.39,0.60,0.27,71.0,98.0,9.0,0.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478,3a1983b3,Fiji,20241123,Ireland,165b36e5,8923cd55,"[0147de23, 117cc1c5, 18853774, 1f45395b, 1ff21...",17.0,52.0,17.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
479,3a1983b3,Fiji,20250830,Tonga,be110f80,b901c3ad,"[0147de23, 07539167, 117cc1c5, 18b260a8, 1f453...",32.0,10.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
480,3a1983b3,Fiji,20250906,Samoa,23778ceb,aa4c09a1,"[0147de23, 07539167, 112c163a, 117cc1c5, 18b26...",29.0,15.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
481,3a1983b3,Fiji,20250915,Canada,1039f7c4,55e97718,"[0147de23, 112c163a, 18b260a8, 1f45395b, 2296d...",10.0,63.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
482,3a1983b3,Fiji,20250921,Japan,f97333f3,19a16e21,"[0147de23, 112c163a, 117cc1c5, 1f45395b, 1ff21...",27.0,33.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
all_players = all_team_stats[['players']]

all_players

                                               players
0    [0042c61a, 01b8ac07, 0e930fa8, 1d490b9e, 252ec...
1    [0042c61a, 01b8ac07, 065c26ea, 0e930fa8, 1d490...
2    [0042c61a, 01b8ac07, 065c26ea, 0e930fa8, 252ec...
3    [065c26ea, 0e930fa8, 1d490b9e, 252ecbf2, 26273...
4    [0042c61a, 065c26ea, 0e930fa8, 1d490b9e, 252ec...
..                                                 ...
478  [0147de23, 117cc1c5, 18853774, 1f45395b, 1ff21...
479  [0147de23, 07539167, 117cc1c5, 18b260a8, 1f453...
480  [0147de23, 07539167, 112c163a, 117cc1c5, 18b26...
481  [0147de23, 112c163a, 18b260a8, 1f45395b, 2296d...
482  [0147de23, 112c163a, 117cc1c5, 1f45395b, 1ff21...

[483 rows x 1 columns]

In [33]:
all_players = all_players[all_players['players'].str.len() > 1]


all_players

                                               players
0    [0042c61a, 01b8ac07, 0e930fa8, 1d490b9e, 252ec...
1    [0042c61a, 01b8ac07, 065c26ea, 0e930fa8, 1d490...
2    [0042c61a, 01b8ac07, 065c26ea, 0e930fa8, 252ec...
3    [065c26ea, 0e930fa8, 1d490b9e, 252ecbf2, 26273...
4    [0042c61a, 065c26ea, 0e930fa8, 1d490b9e, 252ec...
..                                                 ...
478  [0147de23, 117cc1c5, 18853774, 1f45395b, 1ff21...
479  [0147de23, 07539167, 117cc1c5, 18b260a8, 1f453...
480  [0147de23, 07539167, 112c163a, 117cc1c5, 18b26...
481  [0147de23, 112c163a, 18b260a8, 1f45395b, 2296d...
482  [0147de23, 112c163a, 117cc1c5, 1f45395b, 1ff21...

[307 rows x 1 columns]

In [34]:
type(all_players)

pandas.core.frame.DataFrame

In [37]:
from itertools import chain

player_stats = pd.DataFrame()

for id in chain.from_iterable(all_players['players']):
    player_stats = pd.concat([player_stats, fetch_player_stats(player_id=id)])

Fetching all player stats for player_id: 0042c61a...
Fetching all player stats for player_id: 01b8ac07...
Fetching all player stats for player_id: 0e930fa8...
Fetching all player stats for player_id: 1d490b9e...
Fetching all player stats for player_id: 252ecbf2...
Fetching all player stats for player_id: 26273081...
Fetching all player stats for player_id: 2c39da94...
Fetching all player stats for player_id: 3c388133...
Fetching all player stats for player_id: 64b1dbeb...
Fetching all player stats for player_id: 714b76d3...
Fetching all player stats for player_id: 71f25ae6...
Fetching all player stats for player_id: 7a9d8e51...
Fetching all player stats for player_id: 8ba10277...
Fetching all player stats for player_id: 8d2ac40f...
Fetching all player stats for player_id: 991bb389...
Fetching all player stats for player_id: 9b5b5a3c...
Fetching all player stats for player_id: be569f12...
Fetching all player stats for player_id: be6163d9...
Fetching all player stats for player_id: c3958443...
Fetching all player stats for player_id: d30fed66...
Fetching all player stats for player_id: d581f227...
Fetching all player stats for player_id: dee2466d...
Fetching all player stats for player_id: e8718ec4...
Fetching all player stats for player_id: 0042c61a...
Fetching all player stats for player_id: 01b8ac07...
Fetching all player stats for player_id: 065c26ea...
Fetching all player stats for player_id: 0e930fa8...
Fetching all player stats for player_id: 1d490b9e...
Fetching all player stats for player_id: 252ecbf2...
Fetching all player stats for player_id: 2c39da94...
Fetching all player stats for player_id: 3c388133...
Fetching all player stats for player_id: 64b1dbeb...
Fetching all player stats for player_id: 714b76d3...
Fetching all player stats for player_id: 71f25ae6...
Fetching all player stats for player_id: 7a9d8e51...
Fetching all player stats for player_id: 8ba10277...
Fetching all player stats for player_id: 8d2ac40f...
Fetching all player stats for player_id: 991bb389...
Fetching all player stats for player_id: 9b5b5a3c...
Fetching all player stats for player_id: be569f12...
Fetching all player stats for player_id: be6163d9...
Fetching all player stats for player_id: c3958443...
Fetching all player stats for player_id: d30fed66...
Fetching all player stats for player_id: d581f227...
Fetching all player stats for player_id: dee2466d...
Fetching all player stats for player_id: e8718ec4...
Fetching all player stats for player_id: 0042c61a...
Fetching all player stats for player_id: 01b8ac07...
Fetching all player stats for player_id: 065c26ea...
Fetching all player stats for player_id: 0e930fa8...
Fetching all player stats for player_id: 252ecbf2...
Fetching all player stats for player_id: 26273081...
Fetching all player stats for player_id: 2c39da94...
Fetching all player stats for player_id: 3c388133...
Fetching all player stats for player_id: 64b1dbeb...
Fetching all player stats for player_id: 714b76d3...
Fetching all player stats for player_id: 71f25ae6...
Fetching all player stats for player_id: 7a9d8e51...
Fetching all player stats for player_id: 8ba10277...
Fetching all player stats for player_id: 8d2ac40f...
Fetching all player stats for player_id: 991bb389...
Fetching all player stats for player_id: 9b5b5a3c...
Fetching all player stats for player_id: be569f12...
Fetching all player stats for player_id: be6163d9...
Fetching all player stats for player_id: c3958443...
Fetching all player stats for player_id: d30fed66...
Fetching all player stats for player_id: d581f227...
Fetching all player stats for player_id: dee2466d...
Fetching all player stats for player_id: e8718ec4...
Fetching all player stats for player_id: 065c26ea...
Fetching all player stats for player_id: 0e930fa8...
Fetching all player stats for player_id: 1d490b9e...
Fetching all player stats for player_id: 252ecbf2...
Fetching all player stats for player_id: 26273081...
Fetching all player stats for player_id: 2c39da94...
Fetching all player stats for player_id: 3c388133...
Fetching all player stats for player_id: 6440018e...
Fetching all player stats for player_id: 64b1dbeb...
Fetching all player stats for player_id: 714b76d3...
Fetching all player stats for player_id: 71f25ae6...
Fetching all player stats for player_id: 7a9d8e51...
Fetching all player stats for player_id: 8521521c...
Fetching all player stats for player_id: 8ba10277...
Fetching all player stats for player_id: 8d2ac40f...
Fetching all player stats for player_id: 991bb389...
Fetching all player stats for player_id: 9b5b5a3c...
Fetching all player stats for player_id: be569f12...
Fetching all player stats for player_id: be6163d9...
Fetching all player stats for player_id: c3958443...
Fetching all player stats for player_id: d581f227...
Fetching all player stats for player_id: dee2466d...
Fetching all player stats for player_id: e8718ec4...
Fetching all player stats for player_id: 0042c61a...
Fetching all player stats for player_id: 065c26ea...
Fetching all player stats for player_id: 0e930fa8...
Fetching all player stats for player_id: 1d490b9e...
Fetching all player stats for player_id: 252ecbf2...
Fetching all player stats for player_id: 26273081...
Fetching all player stats for player_id: 2c39da94...
Fetching all player stats for player_id: 3c388133...
Fetching all player stats for player_id: 64b1dbeb...
Fetching all player stats for player_id: 714b76d3...
Fetching all player stats for player_id: 71f25ae6...
Fetching all player stats for player_id: 7a9d8e51...
Fetching all player stats for player_id: 8521521c...
Fetching all player stats for player_id: 8ba10277...
Fetching all player stats for player_id: 8d2ac40f...
Fetching all player stats for player_id: 991bb389...
Fetching all player stats for player_id: 9b5b5a3c...
Fetching all player stats for player_id: be569f12...
Fetching all player stats for player_id: c3958443...
Fetching all player stats for player_id: d30fed66...
Fetching all player stats for player_id: d581f227...
Fetching all player stats for player_id: dee2466d...
Fetching all player stats for player_id: e8718ec4...
Fetching all player stats for player_id: 0042c61a...
Fetching all player stats for player_id: 03b2a75c...
Fetching all player stats for player_id: 065c26ea...
Fetching all player stats for player_id: 083d28be...
Fetching all player stats for player_id: 0e930fa8...
Fetching all player stats for player_id: 1d66f423...
Fetching all player stats for player_id: 25974b3c...
Fetching all player stats for player_id: 30b79e7c...
Fetching all player stats for player_id: 3c7620ca...
Fetching all player stats for player_id: 497e679e...
Fetching all player stats for player_id: 64b1dbeb...
Fetching all player stats for player_id: 714b76d3...
Fetching all player stats for player_id: 71f25ae6...
Fetching all player stats for player_id: 7a9d8e51...
Fetching all player stats for player_id: 8d2ac40f...
Fetching all player stats for player_id: 991bb389...
Fetching all player stats for player_id: b05a23f1...
Fetching all player stats for player_id: b4305299...
Fetching all player stats for player_id: be569f12...
Fetching all player stats for player_id: be6163d9...
Fetching all player stats for player_id: d30fed66...
Fetching all player stats for player_id: d581f227...
Fetching all player stats for player_id: dee2466d...
Fetching all player stats for player_id: 0042c61a...
Fetching all player stats for player_id: 065c26ea...
Fetching all player stats for player_id: 083d28be...
Fetching all player stats for player_id: 0e930fa8...
Fetching all player stats for player_id: 1d66f423...
Fetching all player stats for player_id: 25974b3c...
Fetching all player stats for player_id: 2c39da94...
Fetching all player stats for player_id: 30b79e7c...
Fetching all player stats for player_id: 3c7620ca...
Fetching all player stats for player_id: 497e679e...
Fetching all player stats for player_id: 64b1dbeb...
Fetching all player stats for player_id: 714b76d3...
Fetching all player stats for player_id: 71f25ae6...
Fetching all player stats for player_id: 7a9d8e51...
Fetching all player stats for player_id: 8d2ac40f...
Fetching all player stats for player_id: 991bb389...
Fetching all player stats for player_id: b05a23f1...
Fetching all player stats for player_id: be569f12...
Fetching all player stats for player_id: be6163d9...
Fetching all player stats for player_id: c5815c3c...
Fetching all player stats for player_id: d30fed66...
Fetching all player stats for player_id: d581f227...
Fetching all player stats for player_id: dee2466d...
Fetching all player stats for player_id: 0042c61a...
Fetching all player stats for player_id: 065c26ea...
Fetching all player stats for player_id: 083d28be...
Fetching all player stats for player_id: 0e930fa8...
Fetching all player stats for player_id: 1d66f423...
Fetching all player stats for player_id: 25974b3c...
Fetching all player stats for player_id: 2c39da94...
Fetching all player stats for player_id: 30b79e7c...
Fetching all player stats for player_id: 3c7620ca...
Fetching all player stats for player_id: 497e679e...
Fetching all player stats for player_id: 64b1dbeb...
Fetching all player stats for player_id: 714b76d3...
Fetching all player stats for player_id: 7a9d8e51...
Fetching all player stats for player_id: 8521521c...
Fetching all player stats for player_id: 8d2ac40f...
Fetching all player stats for player_id: 991bb389...
Fetching all player stats for player_id: b05a23f1...
Fetching all player stats for player_id: be569f12...
Fetching all player stats for player_id: be6163d9...
Fetching all player stats for player_id: c5815c3c...
Fetching all player stats for player_id: d30fed66...
Fetching all player stats for player_id: d581f227...
Fetching all player stats for player_id: dee2466d...
Fetching all player stats for player_id: 0042c61a...
Fetching all player stats for player_id: 065c26ea...
Fetching all player stats for player_id: 083d28be...
Fetching all player stats for player_id: 0e930fa8...
Fetching all player stats for player_id: 1d66f423...
Fetching all player stats for player_id: 25974b3c...
Fetching all player stats for player_id: 26273081...
Fetching all player stats for player_id: 2c39da94...
Fetching all player stats for player_id: 30b79e7c...
Fetching all player stats for player_id: 3c388133...
Fetching all player stats for player_id: 497e679e...
Fetching all player stats for player_id: 64b1dbeb...
Fetching all player stats for player_id: 714b76d3...
Fetching all player stats for player_id: 7a9d8e51...
Fetching all player stats for player_id: 991bb389...
Fetching all player stats for player_id: 9b5b5a3c...
Fetching all player stats for player_id: a5ce7b34...
Fetching all player stats for player_id: be569f12...
Fetching all player stats for player_id: be6163d9...
Fetching all player stats for player_id: c3958443...
Fetching all player stats for player_id: d30fed66...
Fetching all player stats for player_id: d581f227...
Fetching all player stats for player_id: dee2466d...
Fetching all player stats for player_id: 0042c61a...
Fetching all player stats for player_id: 065c26ea...
Fetching all player stats for player_id: 083d28be...
Fetching all player stats for player_id: 0e930fa8...
Fetching all player stats for player_id: 1d66f423...
Fetching all player stats for player_id: 25974b3c...
Fetching all player stats for player_id: 26273081...
Fetching all player stats for player_id: 2c39da94...
Fetching all player stats for player_id: 30b79e7c...
Fetching all player stats for player_id: 32a43615...
Fetching all player stats for player_id: 3c388133...
Fetching all player stats for player_id: 497e679e...
Fetching all player stats for player_id: 714b76d3...
Fetching all player stats for player_id: 71f25ae6...
Fetching all player stats for player_id: 7a9d8e51...
Fetching all player stats for player_id: 991bb389...
Fetching all player stats for player_id: 9b5b5a3c...
Fetching all player stats for player_id: be569f12...
Fetching all player stats for player_id: be6163d9...
Fetching all player stats for player_id: c3958443...
Fetching all player stats for player_id: d30fed66...
Fetching all player stats for player_id: d581f227...
Fetching all player stats for player_id: dee2466d...
Fetching all player stats for player_id: 0042c61a...
Fetching all player stats for player_id: 083d28be...
Fetching all player stats for player_id: 26273081...
Fetching all player stats for player_id: 2c39da94...
Fetching all player stats for player_id: 3c388133...
Fetching all player stats for player_id: 3c7620ca...
Fetching all player stats for player_id: 497e679e...
Fetching all player stats for player_id: 4988ecdd...
Fetching all player stats for player_id: 5662ef22...
Fetching all player stats for player_id: 64b1dbeb...
Fetching all player stats for player_id: 71f25ae6...
Fetching all player stats for player_id: 7a9d8e51...
Fetching all player stats for player_id: 8ba10277...
Fetching all player stats for player_id: 972ae703...
Fetching all player stats for player_id: 991bb389...
Fetching all player stats for player_id: 9b5b5a3c...
Fetching all player stats for player_id: a5ce7b34...
Fetching all player stats for player_id: b4305299...
Fetching all player stats for player_id: be569f12...
Fetching all player stats for player_id: be6163d9...
Fetching all player stats for player_id: d30fed66...
Fetching all player stats for player_id: d5784e57...
Fetching all player stats for player_id: d581f227...
Fetching all player stats for player_id: dee2466d...
Fetching all player stats for player_id: 0042c61a...
Fetching all player stats for player_id: 26273081...
Fetching all player stats for player_id: 2c39da94...
Fetching all player stats for player_id: 3c388133...
Fetching all player stats for player_id: 3c7620ca...
Fetching all player stats for player_id: 497e679e...
Fetching all player stats for player_id: 4988ecdd...
Fetching all player stats for player_id: 5662ef22...
Fetching all player stats for player_id: 71f25ae6...
Fetching all player stats for player_id: 7a9d8e51...
Fetching all player stats for player_id: 8ba10277...
Fetching all player stats for player_id: 972ae703...
Fetching all player stats for player_id: 991bb389...
Fetching all player stats for player_id: 9b5b5a3c...
Fetching all player stats for player_id: a3d002a3...
Fetching all player stats for player_id: a5ce7b34...
Fetching all player stats for player_id: b4305299...
Fetching all player stats for player_id: be569f12...
Fetching all player stats for player_id: be6163d9...
Fetching all player stats for player_id: d5784e57...
Fetching all player stats for player_id: d581f227...
Fetching all player stats for player_id: d8fe06bd...
Fetching all player stats for player_id: dee2466d...
Fetching all player stats for player_id: 0042c61a...
Fetching all player stats for player_id: 26273081...
Fetching all player stats for player_id: 2c39da94...
Fetching all player stats for player_id: 3c388133...
Fetching all player stats for player_id: 3c7620ca...
Fetching all player stats for player_id: 497e679e...
Fetching all player stats for player_id: 4988ecdd...
Fetching all player stats for player_id: 5662ef22...
Fetching all player stats for player_id: 5d5b9668...
Fetching all player stats for player_id: 6440018e...
Fetching all player stats for player_id: 71f25ae6...
Fetching all player stats for player_id: 7a9d8e51...
Fetching all player stats for player_id: 8ba10277...
Fetching all player stats for player_id: 991bb389...
Fetching all player stats for player_id: 9b5b5a3c...
Fetching all player stats for player_id: a3d002a3...
Fetching all player stats for player_id: a5ce7b34...
Fetching all player stats for player_id: b4305299...
Fetching all player stats for player_id: be569f12...
Fetching all player stats for player_id: be6163d9...
Fetching all player stats for player_id: d30fed66...
Fetching all player stats for player_id: d5784e57...
Fetching all player stats for player_id: d8fe06bd...
Fetching all player stats for player_id: dee2466d...
Fetching all player stats for player_id: 0042c61a...
Fetching all player stats for player_id: 065c26ea...
Fetching all player stats for player_id: 23661b3d...
Fetching all player stats for player_id: 2c39da94...
Fetching all player stats for player_id: 3c388133...
Fetching all player stats for player_id: 497e679e...
Fetching all player stats for player_id: 4988ecdd...
Fetching all player stats for player_id: 5de7936c...
Fetching all player stats for player_id: 71f25ae6...
Fetching all player stats for player_id: 7a9d8e51...
Fetching all player stats for player_id: 89b75fac...
Fetching all player stats for player_id: 991bb389...
Fetching all player stats for player_id: 9b5b5a3c...
Fetching all player stats for player_id: a3d002a3...
Fetching all player stats for player_id: aa669083...
Fetching all player stats for player_id: b4305299...
Fetching all player stats for player_id: be569f12...
Fetching all player stats for player_id: be6163d9...
Fetching all player stats for player_id: d30fed66...
Fetching all player stats for player_id: d5784e57...
Fetching all player stats for player_id: d581f227...
Fetching all player stats for player_id: d8fe06bd...
Fetching all player stats for player_id: dee2466d...
Fetching all player stats for player_id: 0042c61a...
Fetching all player stats for player_id: 065c26ea...
Fetching all player stats for player_id: 23661b3d...
Fetching all player stats for player_id: 2c39da94...
Fetching all player stats for player_id: 3c388133...
Fetching all player stats for player_id: 497e679e...
Fetching all player stats for player_id: 4988ecdd...
Fetching all player stats for player_id: 5de7936c...
Fetching all player stats for player_id: 71f25ae6...
Fetching all player stats for player_id: 7a9d8e51...
Fetching all player stats for player_id: 89b75fac...
Fetching all player stats for player_id: 991bb389...
Fetching all player stats for player_id: 9b5b5a3c...
Fetching all player stats for player_id: a3d002a3...
Fetching all player stats for player_id: aa669083...
Fetching all player stats for player_id: b4305299...
Fetching all player stats for player_id: be569f12...
Fetching all player stats for player_id: be6163d9...
Fetching all player stats for player_id: d30fed66...
Fetching all player stats for player_id: d5784e57...
Fetching all player stats for player_id: d581f227...
Fetching all player stats for player_id: d8fe06bd...
Fetching all player stats for player_id: dee2466d...
Fetching all player stats for player_id: 01b8ac07...
Fetching all player stats for player_id: 0ec1702e...
Fetching all player stats for player_id: 203fc71a...
Fetching all player stats for player_id: 210812d9...
Fetching all player stats for player_id: 252ecbf2...
Fetching all player stats for player_id: 274273b1...
Fetching all player stats for player_id: 2bca4a65...
Fetching all player stats for player_id: 5662ef22...
Fetching all player stats for player_id: 6652fb99...
Fetching all player stats for player_id: 677abbef...
Fetching all player stats for player_id: 8693282a...
Fetching all player stats for player_id: 89b75fac...
Fetching all player stats for player_id: a3d002a3...
Fetching all player stats for player_id: aa669083...
Fetching all player stats for player_id: b05a23f1...
Fetching all player stats for player_id: b34708b6...
Fetching all player stats for player_id: c3958443...
Fetching all player stats for player_id: c5815c3c...
Fetching all player stats for player_id: ca433863...
Fetching all player stats for player_id: d03fe8e2...
Fetching all player stats for player_id: d12fd9df...
Fetching all player stats for player_id: e9344d6c...
Fetching all player stats for player_id: 01b8ac07...
Fetching all player stats for player_id: 06096b5f...
Fetching all player stats for player_id: 1624ae5f...
Fetching all player stats for player_id: 2039e5a2...
Fetching all player stats for player_id: 25514166...
Fetching all player stats for player_id: 403d436f...
Fetching all player stats for player_id: 4551f3d0...
Fetching all player stats for player_id: 55bfc5e2...

In [40]:
test_player_stats = player_stats[player_stats['team_id'].isin(test_nations['team_id'])]


test_player_stats

,player_id,name,team,team_id,position,carries,line_breaks,tackles_completed,turnovers_lost,turnovers_won,...,runs,tackles,total_free_kicks_conceded,total_lineouts,turnover_knock_on,turnovers_conceded,player_name,want_team,want_teamvs,minutes_played
22,0042c61a,Damian Penaud,France,67d88578,wing,1.0,1.0,NaN,NaN,NaN,...,1.0,5.0,0.0,0.0,0.0,0.0,None,67d88578,4409215c,NaN
27,0042c61a,Damian Penaud,France,67d88578,wing,4.0,2.0,1.0,3.0,0.0,...,4.0,1.0,0.0,0.0,2.0,3.0,None,67d88578,165b36e5,NaN
28,0042c61a,Damian Penaud,France,67d88578,wing,8.0,2.0,NaN,NaN,NaN,...,8.0,5.0,0.0,0.0,2.0,2.0,None,67d88578,d0cffe5e,NaN
30,0042c61a,Damian Penaud,France,67d88578,wing,11.0,3.0,6.0,1.0,1.0,...,11.0,6.0,0.0,0.0,1.0,1.0,None,67d88578,094dae60,NaN
31,0042c61a,Damian Penaud,France,67d88578,wing,9.0,1.0,NaN,NaN,NaN,...,9.0,6.0,0.0,1.0,1.0,1.0,None,67d88578,165b36e5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,fd05cd82,Mesake Doge,Fiji,3a1983b3,tighthead_prop,2.0,0.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,None,3a1983b3,be110f80,NaN
35,fd05cd82,Mesake Doge,Fiji,3a1983b3,tighthead_prop,3.0,0.0,4.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,None,3a1983b3,d75e45cc,NaN
36,fd05cd82,Mesake Doge,Fiji,3a1983b3,prop,3.0,0.0,3.0,0.0,1.0,...,3.0,3.0,0.0,0.0,0.0,0.0,None,3a1983b3,5149996e,NaN
40,fd05cd82,Mesake Doge,Fiji,3a1983b3,prop,2.0,0.0,0.0,0.0,0.0,...,2.0,0.0,0.0,0.0,0.0,0.0,None,3a1983b3,094dae60,NaN
41,fd05cd82,Mesake Doge,Fiji,3a1983b3,prop,1.0,0.0,2.0,0.0,0.0,...,1.0,2.0,0.0,0.0,0.0,0.0,None,3a1983b3,b904fef9,NaN