In [4]:
pip install rugbypy

Requirement already satisfied: rugbypy in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.0.0)
Requirement already satisfied: fastcore in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from rugbypy) (1.11.4)
Requirement already satisfied: pandas==2.3.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from rugbypy) (2.3.3)
Requirement already satisfied: pyarrow==19.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from rugbypy) (19.0.0)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from rugbypy) (2.32.5)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas==2.3.3->rugbypy) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/markyan/Library/Python/3.13/lib/python/site-packages (from pandas==2.3.3->rugbypy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas==2.3.3->rugbypy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas==2.3.3->rugbypy) (2025.3)
Requirement already satisfied: packaging in /Users/markyan/Library/Python/3.13/lib/python/site-packages (from fastcore->rugbypy) (25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->rugbypy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->rugbypy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->rugbypy) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->rugbypy) (2024.12.14)
Requirement already satisfied: six>=1.5 in /Users/markyan/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas==2.3.3->rugbypy) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: pip3.13 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [5]:
from rugbypy.match import *
from rugbypy.competition import *
from rugbypy.team import *
from rugbypy.venue import *
from rugbypy.player import *

In [6]:
import pandas as pd

In [7]:
competitions = fetch_all_competitions()


competitions

Fetching all competition...

   competition_id              competition_name
0        ab1bbd78     United Rugby Championship
1        423a2845        The Rugby Championship
2        7a1361e7                   Six Nations
3        38d2154f  European Rugby Champions Cup
4        deb277b2  European Rugby Challenge Cup
5        1b875d20         Gallagher Premiership
6        d0f3c9d2                 French Top 14
7        cacc1678           Super Rugby Pacific
8        08761517                  Mitre 10 Cup
9        5903b8d4            Major League Rugby
10       15f804f7  British and Irish Lions Tour
11       96c775f2      International Test Match
12       5a4d4920               Rugby World Cup
13       ae2a0d13       Women's Rugby World Cup
14       5c60fbdf                   URBA Top 14
15       f1ce3e49                      Men's 7s
16       eb5e37d0                    Women's 7s
17       e6cab2f3           Women's Six Nations
18       25c90071               U20 Six Nations
19       ed4b1e47  World Rugby U20 Championship
20       d1999468           Pacific Nations Cup
21       ba493361           Pacific Four Series
22       f44ef210         Autumn Nations Series
23       f5b03bf0        Women's Internationals
24       05d59524     Rugby Europe Championship
25       dda92478                         WXV 1
26       ddd20248                         WXV 2
27       ee0dd8ca                         WXV 3
28       690eb70a     Premiership Women's Rugby
29       15d56a95               Premiership Cup
30       91f4b76e                        Pro D2
31       5aa5983c        Japan Rugby League One
32       62772efd                    Currie Cup

In [8]:
test_match_ids = ['96c775f2', '423a2845', 'f44ef210', '7a1361e7', '5a4d4920', 'd1999468', '05d59524', '15f804f7']


test_match_names = competitions.loc[competitions['competition_id'].isin(test_match_ids)]

test_match_names

   competition_id              competition_name
1        423a2845        The Rugby Championship
2        7a1361e7                   Six Nations
10       15f804f7  British and Irish Lions Tour
11       96c775f2      International Test Match
12       5a4d4920               Rugby World Cup
20       d1999468           Pacific Nations Cup
22       f44ef210         Autumn Nations Series
24       05d59524     Rugby Europe Championship

In [9]:
matches = fetch_all_matches()

matches

Fetching all matches...

      match_id          home_team           away_team      date
6460  cd8cc265        Sale Sharks               Wasps  20220101
2365  494f4092           Scarlets             Ospreys  20220101
3743  77e4e537           Connacht             Munster  20220101
2052  407da832  Clermont Auvergne    Stade Toulousain  20220101
6368  cae3129b      Exeter Chiefs       Bristol Rugby  20220101
...        ...                ...                 ...       ...
2864  5c416c8d          Northland              Tasman  20260830
7964  41808cec      Bristol Bears    Gloucester Rugby  20260905
7963  9e06320e           Saracens  Northampton Saints  20260905
7962  92fb74b8       Harlequin FC    Leicester Tigers  20260905
7965  ec48ff80        Sale Sharks          Bath Rugby  20260906

[8066 rows x 4 columns]

In [10]:
six_nations_md_5 = fetch_matches_by_date(date = "20250315")

six_nations_md_5 = six_nations_md_5.loc[six_nations_md_5['competition_id'].isin(test_match_ids)]

six_nations_md_5

Fetching matches on date: 20250315...

    match_id competition_id home_team_id home_team away_team_id away_team
4   3693cfdf       7a1361e7     67d88578    France     4409215c  Scotland
8   80928ead       7a1361e7     094dae60     Wales     f60f757d   England
12  d6fcbafa       7a1361e7     d0cffe5e     Italy     165b36e5   Ireland

In [11]:
home_teams = six_nations_md_5[['home_team_id', 'home_team']]
away_teams = six_nations_md_5[['away_team_id', 'away_team']]

home_teams = home_teams.rename(columns={'home_team_id': 'team_id', 'home_team': 'team_name'})
away_teams = away_teams.rename(columns = {'away_team_id': 'team_id', 'away_team': 'team_name'})

In [12]:
six_nations_teams = pd.concat([home_teams, away_teams], ignore_index=True)
six_nations_teams

    team_id team_name
0  67d88578    France
1  094dae60     Wales
2  d0cffe5e     Italy
3  4409215c  Scotland
4  f60f757d   England
5  165b36e5   Ireland

In [13]:
trc_md_1 = fetch_matches_by_date(date = '20250816')

trc_md_1 = trc_md_1.loc[trc_md_1['competition_id'].isin(test_match_ids)]

Fetching matches on date: 20250816...

In [14]:
trc_md_1

,match_id,competition_id,home_team_id,home_team,away_team_id,away_team
0,16fb0c16,423a2845,9b93d911,South Africa,b904fef9,Australia
4,6a36aeb1,423a2845,11392c0c,Argentina,d75e45cc,New Zealand

In [15]:
home_trc = trc_md_1[['home_team_id', 'home_team']]
away_trc = trc_md_1[['away_team_id', 'away_team']]

home_trc = home_trc.rename(columns={'home_team_id': 'team_id', 'home_team': 'team_name'})
away_trc = away_trc.rename(columns={'away_team_id': 'team_id', 'away_team': 'team_name'})

trc_nations = pd.concat([home_trc, away_trc], ignore_index=True)

In [16]:
trc_nations

    team_id     team_name
0  9b93d911  South Africa
1  11392c0c     Argentina
2  b904fef9     Australia
3  d75e45cc   New Zealand

In [17]:
test_nations = pd.concat([six_nations_teams, trc_nations], ignore_index=True)

test_nations

    team_id     team_name
0  67d88578        France
1  094dae60         Wales
2  d0cffe5e         Italy
3  4409215c      Scotland
4  f60f757d       England
5  165b36e5       Ireland
6  9b93d911  South Africa
7  11392c0c     Argentina
8  b904fef9     Australia
9  d75e45cc   New Zealand

In [18]:
british_irish_lions = fetch_matches_by_date(date = '20250719')

british_irish_lions = british_irish_lions.loc[british_irish_lions['competition_id'].isin(test_match_ids)]

Fetching matches on date: 20250719...

In [19]:
british_irish_lions = british_irish_lions[['away_team_id', 'away_team']].rename(columns={'away_team_id': 'team_id', 'away_team': 'team_name'})

In [20]:
british_irish_lions

    team_id                team_name
1  a924d2bc  British and Irish Lions

In [21]:
test_nations = pd.concat([test_nations, british_irish_lions], ignore_index=True)

In [22]:
test_nations

     team_id                team_name
0   67d88578                   France
1   094dae60                    Wales
2   d0cffe5e                    Italy
3   4409215c                 Scotland
4   f60f757d                  England
5   165b36e5                  Ireland
6   9b93d911             South Africa
7   11392c0c                Argentina
8   b904fef9                Australia
9   d75e45cc              New Zealand
10  a924d2bc  British and Irish Lions

In [23]:
rwc_23_09_10 = fetch_matches_by_date(date="20230910")

rwc_23_09_10 = rwc_23_09_10.loc[rwc_23_09_10['competition_id'].isin(test_match_ids)]

Fetching matches on date: 20230910...

In [24]:
rwc_23_09_10

   match_id competition_id home_team_id     home_team away_team_id away_team
1  2eb588d2       5a4d4920     f97333f3         Japan     53ea6ee8     Chile
4  75ff92d0       5a4d4920     9b93d911  South Africa     4409215c  Scotland
6  d1cc85d2       5a4d4920     094dae60         Wales     3a1983b3      Fiji

In [25]:
japan = rwc_23_09_10[rwc_23_09_10['home_team'] == "Japan"]

japan = japan[['home_team_id', 'home_team']].rename(columns={'home_team_id': 'team_id', 'home_team': 'team_name'})

In [26]:
japan

    team_id team_name
1  f97333f3     Japan

In [27]:
fiji = rwc_23_09_10[rwc_23_09_10['away_team'] == "Fiji"]

fiji = fiji[['away_team_id', 'away_team']].rename(columns = {'away_team_id': 'team_id', 'away_team': 'team_name'})

In [28]:
fiji

    team_id team_name
6  3a1983b3      Fiji

In [29]:
test_nations = pd.concat([test_nations, japan, fiji], ignore_index=True)

test_nations

     team_id                team_name
0   67d88578                   France
1   094dae60                    Wales
2   d0cffe5e                    Italy
3   4409215c                 Scotland
4   f60f757d                  England
5   165b36e5                  Ireland
6   9b93d911             South Africa
7   11392c0c                Argentina
8   b904fef9                Australia
9   d75e45cc              New Zealand
10  a924d2bc  British and Irish Lions
11  f97333f3                    Japan
12  3a1983b3                     Fiji

In [31]:
france_team_stats = fetch_team_stats(team_id='67d88578')

france_team_stats

Fetching all team stats for team_id: 67d88578...

,team_id,team,game_date,team_vs,team_vs_id,match_id,players,score,team_vs_score,22m_entries,...,offload,pc_possession_first,pc_possession_second,pc_territory_first,pc_territory_second,rucks_total,runs,scrums_total,total_free_kicks_conceded,turnover_knock_on
0,67d88578,France,20220206,Italy,d0cffe5e,4a49c716,"[0042c61a, 01b8ac07, 0e930fa8, 1d490b9e, 252ec...",NaN,NaN,NaN,...,9.0,0.62,0.54,0.66,0.64,96.0,124.0,5.0,0.0,7.0
1,67d88578,France,20220212,Ireland,165b36e5,71ccf2fb,"[0042c61a, 01b8ac07, 065c26ea, 0e930fa8, 1d490...",NaN,NaN,NaN,...,8.0,0.52,0.43,0.55,0.48,83.0,101.0,5.0,1.0,7.0
2,67d88578,France,20220226,Scotland,4409215c,eb863c39,"[0042c61a, 01b8ac07, 065c26ea, 0e930fa8, 252ec...",NaN,NaN,NaN,...,10.0,0.45,0.39,0.39,0.61,41.0,75.0,9.0,1.0,6.0
3,67d88578,France,20220311,Wales,094dae60,6b6585fc,"[065c26ea, 0e930fa8, 1d490b9e, 252ecbf2, 26273...",NaN,NaN,NaN,...,10.0,0.53,0.41,0.55,0.33,69.0,98.0,6.0,1.0,9.0
4,67d88578,France,20220319,England,f60f757d,cc3c0a71,"[0042c61a, 065c26ea, 0e930fa8, 1d490b9e, 252ec...",NaN,NaN,NaN,...,13.0,0.51,0.39,0.60,0.27,71.0,98.0,9.0,0.0,8.0
5,67d88578,France,20220702,Japan,f97333f3,51fa68f7,[],23.0,42.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,67d88578,France,20220709,Japan,f97333f3,ee70bf1c,[],15.0,20.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,67d88578,France,20221105,Australia,b904fef9,8e0c66c0,[],29.0,30.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,67d88578,France,20221112,South Africa,9b93d911,9e961065,[],30.0,26.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,67d88578,France,20221120,Japan,f97333f3,44feca36,[],35.0,17.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,67d88578,France,20230205,Italy,d0cffe5e,f9871df9,"[0042c61a, 03b2a75c, 065c26ea, 083d28be, 0e930...",NaN,NaN,NaN,...,11.0,0.47,0.40,0.56,0.60,70.0,107.0,2.0,1.0,16.0
11,67d88578,France,20230211,Ireland,165b36e5,de63aaca,"[0042c61a, 065c26ea, 083d28be, 0e930fa8, 1d66f...",NaN,NaN,NaN,...,12.0,0.48,0.44,0.32,0.39,88.0,136.0,1.0,1.0,11.0
12,67d88578,France,20230226,Scotland,4409215c,6dee3de9,"[0042c61a, 065c26ea, 083d28be, 0e930fa8, 1d66f...",NaN,NaN,NaN,...,5.0,0.45,0.45,0.34,0.45,66.0,100.0,7.0,0.0,3.0
13,67d88578,France,20230311,England,f60f757d,cb76c12f,"[0042c61a, 065c26ea, 083d28be, 0e930fa8, 1d66f...",NaN,NaN,NaN,...,11.0,0.53,0.41,0.45,0.44,71.0,108.0,9.0,3.0,13.0
14,67d88578,France,20230318,Wales,094dae60,df41ed1f,"[0042c61a, 065c26ea, 083d28be, 0e930fa8, 1d66f...",NaN,NaN,NaN,...,6.0,0.43,0.50,0.32,0.67,78.0,107.0,5.0,0.0,11.0
15,67d88578,France,20230908,New Zealand,d75e45cc,8f7b5d57,[2c39da94],NaN,NaN,6.0,...,11.0,0.44,0.53,0.44,0.78,59.0,104.0,5.0,1.0,5.0
16,67d88578,France,20230914,Uruguay,95ba991c,b5bdbe84,[2c39da94],NaN,NaN,15.0,...,9.0,0.66,0.39,0.63,0.32,53.0,105.0,13.0,1.0,7.0
17,67d88578,France,20230921,Namibia,03b35a84,cbf340fc,[2c39da94],NaN,NaN,20.0,...,10.0,0.51,0.53,0.48,0.27,42.0,124.0,5.0,0.0,10.0
18,67d88578,France,20231006,Italy,d0cffe5e,e235c804,[2c39da94],NaN,NaN,13.0,...,10.0,0.56,0.57,0.57,0.60,90.0,143.0,7.0,1.0,3.0
19,67d88578,France,20231015,South Africa,9b93d911,a92e8c48,[2c39da94],NaN,NaN,11.0,...,13.0,0.59,0.60,0.73,0.56,108.0,154.0,9.0,1.0,10.0
20,67d88578,France,20240202,Ireland,165b36e5,48f165d0,"[0042c61a, 083d28be, 26273081, 2c39da94, 3c388...",NaN,NaN,5.0,...,7.0,0.47,0.42,0.41,0.57,77.0,93.0,2.0,1.0,8.0
21,67d88578,France,20240210,Scotland,4409215c,5adf0a01,"[0042c61a, 26273081, 2c39da94, 3c388133, 3c762...",NaN,NaN,9.0,...,4.0,0.43,0.45,0.46,0.49,79.0,89.0,4.0,1.0,8.0
22,67d88578,France,20240225,Italy,d0cffe5e,c850930c,"[0042c61a, 26273081, 2c39da94, 3c388133, 3c762...",NaN,NaN,10.0,...,13.0,0.58,0.47,0.69,0.46,104.0,138.0,5.0,1.0,11.0
23,67d88578,France,20240310,Wales,094dae60,4deaa73c,"[0042c61a, 065c26ea, 23661b3d, 2c39da94, 3c388...",NaN,NaN,4.0,...,11.0,0.62,0.50,0.60,0.73,106.0,140.0,11.0,1.0,4.0
24,67d88578,France,20240316,England,f60f757d,a9335d7e,"[0042c61a, 065c26ea, 23661b3d, 2c39da94, 3c388...",NaN,NaN,6.0,...,10.0,0.55,0.62,0.51,0.56,92.0,125.0,3.0,1.0,8.0
25,67d88578,France,20240706,Argentina,11392c0c,5ba57b40,"[01b8ac07, 0ec1702e, 203fc71a, 210812d9, 252ec...",28.0,13.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,67d88578,France,20240710,Uruguay,95ba991c,776d4f68,"[01b8ac07, 06096b5f, 1624ae5f, 2039e5a2, 25514...",43.0,28.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,67d88578,France,20240713,Argentina,11392c0c,9488560d,"[01b8ac07, 0ec1702e, 203fc71a, 252ecbf2, 27427...",25.0,33.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,67d88578,France,20241109,Japan,f97333f3,edd253ae,[2c39da94],52.0,12.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,67d88578,France,20241116,New Zealand,d75e45cc,2db0a740,[],30.0,29.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,67d88578,France,20241122,Argentina,11392c0c,81ef09ad,"[065c26ea, 083d28be, 1d490b9e, 203fc71a, 23661...",37.0,23.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,67d88578,France,20250131,Wales,094dae60,e0e8dc1b,"[0e930fa8, 0ec1702e, 203fc71a, 210812d9, 23661...",NaN,NaN,NaN,...,13.0,0.58,0.42,0.71,0.37,104.0,143.0,7.0,2.0,13.0
32,67d88578,France,20250208,England,f60f757d,5ae51188,[2c39da94],NaN,NaN,NaN,...,9.0,0.55,0.45,0.58,0.50,74.0,134.0,5.0,1.0,16.0
33,67d88578,France,20250223,Italy,d0cffe5e,f50ddcdd,"[065c26ea, 0ec1702e, 203fc71a, 210812d9, 252ec...",NaN,NaN,NaN,...,27.0,0.61,0.64,0.53,0.67,110.0,168.0,5.0,1.0,8.0
34,67d88578,France,20250308,Ireland,165b36e5,5222ebe1,"[0042c61a, 065c26ea, 0e930fa8, 203fc71a, 21081...",NaN,NaN,NaN,...,9.0,0.40,0.44,0.47,0.48,66.0,96.0,3.0,2.0,3.0
35,67d88578,France,20250315,Scotland,4409215c,3693cfdf,"[0042c61a, 065c26ea, 0e930fa8, 203fc71a, 21081...",NaN,NaN,NaN,...,5.0,0.45,0.44,0.54,0.48,72.0,87.0,2.0,0.0,4.0
36,67d88578,France,20260205,Ireland,165b36e5,af7c5c4e,"[0ec1702e, 203fc71a, 210812d9, 2265e707, 23661...",36.0,14.0,13.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,67d88578,France,20260215,Wales,094dae60,faa9e528,"[065c26ea, 08ffbbd3, 0ec1702e, 203fc71a, 21081...",NaN,NaN,5.0,...,25.0,0.46,0.50,0.62,0.57,86.0,155.0,3.0,1.0,8.0
38,67d88578,France,20260222,Italy,d0cffe5e,0641a6bf,"[065c26ea, 0ec1702e, 203fc71a, 210812d9, 2265e...",33.0,8.0,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,67d88578,France,20260307,Scotland,4409215c,9203ce59,"[01b8ac07, 065c26ea, 0ec1702e, 203fc71a, 21081...",40.0,50.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,67d88578,France,20260314,England,f60f757d,825da9e7,"[01b8ac07, 065c26ea, 0ec1702e, 203fc71a, 2265e...",48.0,46.0,10.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
all_matches = fetch_all_matches()

all_matches

tier_1_test_matches = all_matches[all_matches['home_team'].isin(test_nations['team_name']) |
                                   all_matches['away_team'].isin(test_nations['team_name'])]

Fetching all matches...

In [35]:
tier_1_test_matches

      match_id     home_team     away_team      date
1237  26eb0d57       Ireland         Wales  20220205
6768  d803469c      Scotland       England  20220205
2386  4a49c716        France         Italy  20220206
3966  7ec3e5e5         Wales      Scotland  20220212
3559  71ccf2fb        France       Ireland  20220212
...        ...           ...           ...       ...
1649  337dd942     Argentina  South Africa  20260808
6016  c09a6180     Australia         Japan  20260815
5001  a215a140  South Africa   New Zealand  20260822
7052  e1440199  South Africa   New Zealand  20260829
3911  7c94492d     Argentina     Australia  20260829

[346 rows x 4 columns]