In [1]:
pip install rugbypy

Requirement already satisfied: rugbypy in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.0.0)
Requirement already satisfied: fastcore in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from rugbypy) (1.11.4)
Requirement already satisfied: pandas==2.3.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from rugbypy) (2.3.3)
Requirement already satisfied: pyarrow==19.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from rugbypy) (19.0.0)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from rugbypy) (2.32.5)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas==2.3.3->rugbypy) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/markyan/Library/Python/3.13/lib/python/site-packages (from pandas==2.3.3->rugbypy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas==2.3.3->rugbypy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas==2.3.3->rugbypy) (2025.3)
Requirement already satisfied: packaging in /Users/markyan/Library/Python/3.13/lib/python/site-packages (from fastcore->rugbypy) (25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->rugbypy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->rugbypy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->rugbypy) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->rugbypy) (2024.12.14)
Requirement already satisfied: six>=1.5 in /Users/markyan/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas==2.3.3->rugbypy) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: pip3.13 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
from rugbypy.match import *
from rugbypy.competition import *
from rugbypy.team import *
from rugbypy.venue import *
from rugbypy.player import *

In [22]:
import pandas as pd

In [4]:
competitions = fetch_all_competitions()


competitions

Fetching all competition...

   competition_id              competition_name
0        ab1bbd78     United Rugby Championship
1        423a2845        The Rugby Championship
2        7a1361e7                   Six Nations
3        38d2154f  European Rugby Champions Cup
4        deb277b2  European Rugby Challenge Cup
5        1b875d20         Gallagher Premiership
6        d0f3c9d2                 French Top 14
7        cacc1678           Super Rugby Pacific
8        08761517                  Mitre 10 Cup
9        5903b8d4            Major League Rugby
10       15f804f7  British and Irish Lions Tour
11       96c775f2      International Test Match
12       5a4d4920               Rugby World Cup
13       ae2a0d13       Women's Rugby World Cup
14       5c60fbdf                   URBA Top 14
15       f1ce3e49                      Men's 7s
16       eb5e37d0                    Women's 7s
17       e6cab2f3           Women's Six Nations
18       25c90071               U20 Six Nations
19       ed4b1e47  World Rugby U20 Championship
20       d1999468           Pacific Nations Cup
21       ba493361           Pacific Four Series
22       f44ef210         Autumn Nations Series
23       f5b03bf0        Women's Internationals
24       05d59524     Rugby Europe Championship
25       dda92478                         WXV 1
26       ddd20248                         WXV 2
27       ee0dd8ca                         WXV 3
28       690eb70a     Premiership Women's Rugby
29       15d56a95               Premiership Cup
30       91f4b76e                        Pro D2
31       5aa5983c        Japan Rugby League One
32       62772efd                    Currie Cup

In [9]:
test_match_ids = ['96c775f2', '423a2845', 'f44ef210', '7a1361e7', '5a4d4920', 'd1999468', '05d59524', '15f804f7']


test_match_names = competitions.loc[competitions['competition_id'].isin(test_match_ids)]

test_match_names

   competition_id              competition_name
1        423a2845        The Rugby Championship
2        7a1361e7                   Six Nations
10       15f804f7  British and Irish Lions Tour
11       96c775f2      International Test Match
12       5a4d4920               Rugby World Cup
20       d1999468           Pacific Nations Cup
22       f44ef210         Autumn Nations Series
24       05d59524     Rugby Europe Championship

In [11]:
matches = fetch_all_matches()

matches

Fetching all matches...

      match_id          home_team           away_team      date
6460  cd8cc265        Sale Sharks               Wasps  20220101
2365  494f4092           Scarlets             Ospreys  20220101
3743  77e4e537           Connacht             Munster  20220101
2052  407da832  Clermont Auvergne    Stade Toulousain  20220101
6368  cae3129b      Exeter Chiefs       Bristol Rugby  20220101
...        ...                ...                 ...       ...
2864  5c416c8d          Northland              Tasman  20260830
7964  41808cec      Bristol Bears    Gloucester Rugby  20260905
7963  9e06320e           Saracens  Northampton Saints  20260905
7962  92fb74b8       Harlequin FC    Leicester Tigers  20260905
7965  ec48ff80        Sale Sharks          Bath Rugby  20260906

[8066 rows x 4 columns]

In [ ]:
six_nations_md_5 = fetch_matches_by_date(date = "20250315")

six_nations_md_5 = six_nations_md_5.loc[six_nations_md_5['competition_id'].isin(test_match_ids)]

six_nations_md_5

Fetching matches on date: 20250315...

   match_id competition_id home_team_id home_team away_team_id away_team
2  d6fcbafa       7a1361e7     d0cffe5e     Italy     165b36e5   Ireland
3  80928ead       7a1361e7     094dae60     Wales     f60f757d   England
4  3693cfdf       7a1361e7     67d88578    France     4409215c  Scotland

In [19]:
home_teams = six_nations_md_5[['home_team_id', 'home_team']]
away_teams = six_nations_md_5[['away_team_id', 'away_team']]

home_teams = home_teams.rename(columns={'home_team_id': 'team_id', 'home_team': 'team_name'})
away_teams = away_teams.rename(columns = {'away_team_id': 'team_id', 'away_team': 'team_name'})

In [23]:
six_nations_teams = pd.concat([home_teams, away_teams], ignore_index=True)
six_nations_teams

    team_id team_name
0  d0cffe5e     Italy
1  094dae60     Wales
2  67d88578    France
3  165b36e5   Ireland
4  f60f757d   England
5  4409215c  Scotland

In [25]:
trc_md_1 = fetch_matches_by_date(date = '20250816')

trc_md_1 = trc_md_1.loc[trc_md_1['competition_id'].isin(test_match_ids)]

Fetching matches on date: 20250816...

In [26]:
trc_md_1

,match_id,competition_id,home_team_id,home_team,away_team_id,away_team
0,16fb0c16,423a2845,446f2243,South Africa,092ba249,Australia
1,6a36aeb1,423a2845,24c0c93d,Argentina,ef10fb4f,New Zealand

In [29]:
home_trc = trc_md_1[['home_team_id', 'home_team']]
away_trc = trc_md_1[['away_team_id', 'away_team']]

home_trc = home_trc.rename(columns={'home_team_id': 'team_id', 'home_team': 'team_name'})
away_trc = away_trc.rename(columns={'away_team_id': 'team_id', 'away_team': 'team_name'})

trc_nations = pd.concat([home_trc, away_trc], ignore_index=True)

In [ ]:
trc_nations

    team_id     team_name
0  446f2243  South Africa
1  24c0c93d     Argentina
2  092ba249     Australia
3  ef10fb4f   New Zealand

In [31]:
test_nations = pd.concat([six_nations_teams, trc_nations], ignore_index=True)

test_nations

    team_id     team_name
0  d0cffe5e         Italy
1  094dae60         Wales
2  67d88578        France
3  165b36e5       Ireland
4  f60f757d       England
5  4409215c      Scotland
6  446f2243  South Africa
7  24c0c93d     Argentina
8  092ba249     Australia
9  ef10fb4f   New Zealand

In [38]:
british_irish_lions = fetch_matches_by_date(date = '20250719')

british_irish_lions = british_irish_lions.loc[british_irish_lions['competition_id'].isin(test_match_ids)]

Fetching matches on date: 20250719...

In [40]:
british_irish_lions = british_irish_lions[['away_team_id', 'away_team']].rename(columns={'away_team_id': 'team_id', 'away_team': 'team_name'})

In [ ]:
british_irish_lions

    team_id                team_name
0  bb49fc47  British and Irish Lions

In [42]:
test_nations = pd.concat([test_nations, british_irish_lions], ignore_index=True)

In [43]:
test_nations

     team_id                team_name
0   d0cffe5e                    Italy
1   094dae60                    Wales
2   67d88578                   France
3   165b36e5                  Ireland
4   f60f757d                  England
5   4409215c                 Scotland
6   446f2243             South Africa
7   24c0c93d                Argentina
8   092ba249                Australia
9   ef10fb4f              New Zealand
10  bb49fc47  British and Irish Lions

In [ ]:
## test cell (testing github:()
## another test commit