In [4]:
pip install rugbypy

Requirement already satisfied: rugbypy in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (3.0.0)
Requirement already satisfied: fastcore in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from rugbypy) (1.11.4)
Requirement already satisfied: pandas==2.3.3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from rugbypy) (2.3.3)
Requirement already satisfied: pyarrow==19.0.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from rugbypy) (19.0.0)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from rugbypy) (2.32.5)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas==2.3.3->rugbypy) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/markyan/Library/Python/3.13/lib/python/site-packages (from pandas==2.3.3->rugbypy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas==2.3.3->rugbypy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas==2.3.3->rugbypy) (2025.3)
Requirement already satisfied: packaging in /Users/markyan/Library/Python/3.13/lib/python/site-packages (from fastcore->rugbypy) (25.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->rugbypy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->rugbypy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->rugbypy) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from requests->rugbypy) (2024.12.14)
Requirement already satisfied: six>=1.5 in /Users/markyan/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas==2.3.3->rugbypy) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: pip3.13 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [5]:
from rugbypy.match import *
from rugbypy.competition import *
from rugbypy.team import *
from rugbypy.venue import *
from rugbypy.player import *

In [6]:
import pandas as pd

In [59]:
competitions = fetch_all_competitions()
venues = fetch_all_venues()

Fetching all competition...
Fetching all venues...

In [60]:
venues.head()

   venue_id                 venue_name
0  be11e8d2                    Unknown
1  bc721fea            Stade du Hameau
2  5b691aae            Stade de France
3  b3faf6cf  Stadio Comunale di Monigo
4  fc3a9a61      at Franklin's Gardens

In [8]:
test_match_ids = ['96c775f2', '423a2845', 'f44ef210', '7a1361e7', '5a4d4920', 'd1999468', '05d59524', '15f804f7']


test_match_names = competitions.loc[competitions['competition_id'].isin(test_match_ids)]

test_match_names

   competition_id              competition_name
1        423a2845        The Rugby Championship
2        7a1361e7                   Six Nations
10       15f804f7  British and Irish Lions Tour
11       96c775f2      International Test Match
12       5a4d4920               Rugby World Cup
20       d1999468           Pacific Nations Cup
22       f44ef210         Autumn Nations Series
24       05d59524     Rugby Europe Championship

In [10]:
six_nations_md_5 = fetch_matches_by_date(date = "20250315")

six_nations_md_5 = six_nations_md_5.loc[six_nations_md_5['competition_id'].isin(test_match_ids)]

six_nations_md_5

Fetching matches on date: 20250315...

    match_id competition_id home_team_id home_team away_team_id away_team
4   3693cfdf       7a1361e7     67d88578    France     4409215c  Scotland
8   80928ead       7a1361e7     094dae60     Wales     f60f757d   England
12  d6fcbafa       7a1361e7     d0cffe5e     Italy     165b36e5   Ireland

In [11]:
home_teams = six_nations_md_5[['home_team_id', 'home_team']]
away_teams = six_nations_md_5[['away_team_id', 'away_team']]

home_teams = home_teams.rename(columns={'home_team_id': 'team_id', 'home_team': 'team_name'})
away_teams = away_teams.rename(columns = {'away_team_id': 'team_id', 'away_team': 'team_name'})

In [12]:
six_nations_teams = pd.concat([home_teams, away_teams], ignore_index=True)
six_nations_teams

    team_id team_name
0  67d88578    France
1  094dae60     Wales
2  d0cffe5e     Italy
3  4409215c  Scotland
4  f60f757d   England
5  165b36e5   Ireland

In [13]:
trc_md_1 = fetch_matches_by_date(date = '20250816')

trc_md_1 = trc_md_1.loc[trc_md_1['competition_id'].isin(test_match_ids)]

Fetching matches on date: 20250816...

In [14]:
trc_md_1

,match_id,competition_id,home_team_id,home_team,away_team_id,away_team
0,16fb0c16,423a2845,9b93d911,South Africa,b904fef9,Australia
4,6a36aeb1,423a2845,11392c0c,Argentina,d75e45cc,New Zealand

In [15]:
home_trc = trc_md_1[['home_team_id', 'home_team']]
away_trc = trc_md_1[['away_team_id', 'away_team']]

home_trc = home_trc.rename(columns={'home_team_id': 'team_id', 'home_team': 'team_name'})
away_trc = away_trc.rename(columns={'away_team_id': 'team_id', 'away_team': 'team_name'})

trc_nations = pd.concat([home_trc, away_trc], ignore_index=True)

In [16]:
trc_nations

    team_id     team_name
0  9b93d911  South Africa
1  11392c0c     Argentina
2  b904fef9     Australia
3  d75e45cc   New Zealand

In [17]:
test_nations = pd.concat([six_nations_teams, trc_nations], ignore_index=True)

test_nations

    team_id     team_name
0  67d88578        France
1  094dae60         Wales
2  d0cffe5e         Italy
3  4409215c      Scotland
4  f60f757d       England
5  165b36e5       Ireland
6  9b93d911  South Africa
7  11392c0c     Argentina
8  b904fef9     Australia
9  d75e45cc   New Zealand

In [18]:
british_irish_lions = fetch_matches_by_date(date = '20250719')

british_irish_lions = british_irish_lions.loc[british_irish_lions['competition_id'].isin(test_match_ids)]

Fetching matches on date: 20250719...

In [19]:
british_irish_lions = british_irish_lions[['away_team_id', 'away_team']].rename(columns={'away_team_id': 'team_id', 'away_team': 'team_name'})

In [20]:
british_irish_lions

    team_id                team_name
1  a924d2bc  British and Irish Lions

In [21]:
test_nations = pd.concat([test_nations, british_irish_lions], ignore_index=True)

In [22]:
test_nations

     team_id                team_name
0   67d88578                   France
1   094dae60                    Wales
2   d0cffe5e                    Italy
3   4409215c                 Scotland
4   f60f757d                  England
5   165b36e5                  Ireland
6   9b93d911             South Africa
7   11392c0c                Argentina
8   b904fef9                Australia
9   d75e45cc              New Zealand
10  a924d2bc  British and Irish Lions

In [23]:
rwc_23_09_10 = fetch_matches_by_date(date="20230910")

rwc_23_09_10 = rwc_23_09_10.loc[rwc_23_09_10['competition_id'].isin(test_match_ids)]

Fetching matches on date: 20230910...

In [24]:
rwc_23_09_10

   match_id competition_id home_team_id     home_team away_team_id away_team
1  2eb588d2       5a4d4920     f97333f3         Japan     53ea6ee8     Chile
4  75ff92d0       5a4d4920     9b93d911  South Africa     4409215c  Scotland
6  d1cc85d2       5a4d4920     094dae60         Wales     3a1983b3      Fiji

In [25]:
japan = rwc_23_09_10[rwc_23_09_10['home_team'] == "Japan"]

japan = japan[['home_team_id', 'home_team']].rename(columns={'home_team_id': 'team_id', 'home_team': 'team_name'})

In [27]:
fiji = rwc_23_09_10[rwc_23_09_10['away_team'] == "Fiji"]

fiji = fiji[['away_team_id', 'away_team']].rename(columns = {'away_team_id': 'team_id', 'away_team': 'team_name'})

In [28]:
fiji

    team_id team_name
6  3a1983b3      Fiji

In [29]:
test_nations = pd.concat([test_nations, japan, fiji], ignore_index=True)

test_nations

     team_id                team_name
0   67d88578                   France
1   094dae60                    Wales
2   d0cffe5e                    Italy
3   4409215c                 Scotland
4   f60f757d                  England
5   165b36e5                  Ireland
6   9b93d911             South Africa
7   11392c0c                Argentina
8   b904fef9                Australia
9   d75e45cc              New Zealand
10  a924d2bc  British and Irish Lions
11  f97333f3                    Japan
12  3a1983b3                     Fiji

In [ ]:
all_matches = fetch_all_matches()

tier_1_test_matches = all_matches[all_matches['home_team'].isin(test_nations['team_name']) |
                                   all_matches['away_team'].isin(test_nations['team_name'])]

Fetching all matches...

In [58]:
tier_1_test_matches.head(5)

      match_id home_team away_team      date
1237  26eb0d57   Ireland     Wales  20220205
6768  d803469c  Scotland   England  20220205
2386  4a49c716    France     Italy  20220206
3966  7ec3e5e5     Wales  Scotland  20220212
3559  71ccf2fb    France   Ireland  20220212

In [57]:
tier_1_test_ids = tier_1_test_matches['match_id']

In [52]:
matches = pd.DataFrame()
for id in tier_1_test_ids:
    matches = pd.concat([matches, fetch_match_details(match_id=id)])

Fetching match details for match_id: 26eb0d57...
Fetching match details for match_id: d803469c...
Fetching match details for match_id: 4a49c716...
Fetching match details for match_id: 7ec3e5e5...
Fetching match details for match_id: 71ccf2fb...
Fetching match details for match_id: c960c247...
Fetching match details for match_id: eb863c39...
Fetching match details for match_id: 0f429181...
Fetching match details for match_id: 4b7ddccc...
Fetching match details for match_id: 6b6585fc...
Fetching match details for match_id: db462616...
Fetching match details for match_id: b50b968e...
Fetching match details for match_id: cc3c0a71...
Fetching match details for match_id: 8e84569c...
Fetching match details for match_id: d82fd124...
Fetching match details for match_id: 57934f49...
Fetching match details for match_id: dc868afb...
Fetching match details for match_id: 06752427...
Fetching match details for match_id: 226e92ee...
Fetching match details for match_id: e7917048...
Fetching match details for match_id: d762f451...
Fetching match details for match_id: 6a8fd5ea...
Fetching match details for match_id: b51e1c95...
Fetching match details for match_id: becb6f0a...
Fetching match details for match_id: 631d877a...
Fetching match details for match_id: ffabf409...
Fetching match details for match_id: 5bc08805...
Fetching match details for match_id: 25c638f4...
Fetching match details for match_id: 6ae96fc3...
Fetching match details for match_id: f5266f66...
Fetching match details for match_id: d4b62a3d...
Fetching match details for match_id: 72940db0...
Fetching match details for match_id: 617b79ab...
Fetching match details for match_id: 861b872e...
Fetching match details for match_id: 99ea4482...
Fetching match details for match_id: 860ce2d2...
Fetching match details for match_id: 9233d4bc...
Fetching match details for match_id: 2864ca3c...
Fetching match details for match_id: f4f5d078...
Fetching match details for match_id: d661c5a6...
Fetching match details for match_id: d8466f79...
Fetching match details for match_id: d2b35ab2...
Fetching match details for match_id: c51fac62...
Fetching match details for match_id: 0c15dfc8...
Fetching match details for match_id: 20335bcb...
Fetching match details for match_id: 123947a9...
Fetching match details for match_id: 6d1606f8...
Fetching match details for match_id: f677444a...
Fetching match details for match_id: bcf07758...
Fetching match details for match_id: bf8d7eb2...
Fetching match details for match_id: 7b7897a3...
Fetching match details for match_id: 5ca98588...
Fetching match details for match_id: 77be9738...
Fetching match details for match_id: 67a2d112...
Fetching match details for match_id: 89c35dc0...
Fetching match details for match_id: 913715cf...
Fetching match details for match_id: a400f833...
Fetching match details for match_id: d6ca6295...
Fetching match details for match_id: 8dd23556...
Fetching match details for match_id: ecdb0b20...
Fetching match details for match_id: a82c5b04...
Fetching match details for match_id: ac4a06dc...
Fetching match details for match_id: a7276a45...
Fetching match details for match_id: 7ee5eb5e...
Fetching match details for match_id: 414549b0...
Fetching match details for match_id: cec1bc03...
Fetching match details for match_id: 2c198294...
Fetching match details for match_id: d8010e99...
Fetching match details for match_id: cecd683b...
Fetching match details for match_id: def0c06a...
Fetching match details for match_id: f9871df9...
Fetching match details for match_id: de63aaca...
Fetching match details for match_id: 3d84a361...
Fetching match details for match_id: 7df54b9d...
Fetching match details for match_id: 21cfd285...
Fetching match details for match_id: ecc22f77...
Fetching match details for match_id: 6dee3de9...
Fetching match details for match_id: 95b53bda...
Fetching match details for match_id: cb76c12f...
Fetching match details for match_id: 1de8bbeb...
Fetching match details for match_id: 19c06d9f...
Fetching match details for match_id: df41ed1f...
Fetching match details for match_id: 8f0c8551...
Fetching match details for match_id: cf78c912...
Fetching match details for match_id: 30109d17...
Fetching match details for match_id: 78895f3c...
Fetching match details for match_id: 9fd72cdb...
Fetching match details for match_id: b19322e3...
Fetching match details for match_id: 30a5749b...
Fetching match details for match_id: d7f50b8c...
Fetching match details for match_id: db1557ec...
Fetching match details for match_id: 2ff3e23c...
Fetching match details for match_id: 13e3095e...
Fetching match details for match_id: 7bad04a3...
Fetching match details for match_id: a0ddfe15...
Fetching match details for match_id: 18542c27...
Fetching match details for match_id: 112cc3a2...
Fetching match details for match_id: ea562663...
Fetching match details for match_id: 50033e53...
Fetching match details for match_id: 28f2124c...
Fetching match details for match_id: f93af1a5...
Fetching match details for match_id: d4fc0a4f...
Fetching match details for match_id: 384e0fd7...
Fetching match details for match_id: 35c15f6b...
Fetching match details for match_id: c7067b6e...
Fetching match details for match_id: 227056b6...
Fetching match details for match_id: db7135be...
Fetching match details for match_id: 66ec9426...
Fetching match details for match_id: 16280106...
Fetching match details for match_id: 73ed7881...
Fetching match details for match_id: 9f0ba4b1...
Fetching match details for match_id: a0150160...
Fetching match details for match_id: be3dcd77...
Fetching match details for match_id: 8804cc54...
Fetching match details for match_id: 101eddeb...
Fetching match details for match_id: 87a56948...
Fetching match details for match_id: 765b65e2...
Fetching match details for match_id: 737e4657...
Fetching match details for match_id: 75ff92d0...
Fetching match details for match_id: 2eb588d2...
Fetching match details for match_id: d1cc85d2...
Fetching match details for match_id: 2dc91e1d...
Fetching match details for match_id: f320ff74...
Fetching match details for match_id: c737be15...
Fetching match details for match_id: 8dee04af...
Fetching match details for match_id: 9861e09e...
Fetching match details for match_id: dafe92a0...
Fetching match details for match_id: 0f667939...
Fetching match details for match_id: 3c81211c...
Fetching match details for match_id: 5bc221ee...
Fetching match details for match_id: fa51d3f6...
Fetching match details for match_id: 61b957ae...
Fetching match details for match_id: fb26ffe1...
Fetching match details for match_id: 657561e9...
Fetching match details for match_id: 3bab9043...
Fetching match details for match_id: 389a52fd...
Fetching match details for match_id: 7dbacb43...
Fetching match details for match_id: c21a4e31...
Fetching match details for match_id: 1230e74e...
Fetching match details for match_id: c326366e...
Fetching match details for match_id: 57112a6a...
Fetching match details for match_id: 14356bd6...
Fetching match details for match_id: 7c9717fe...
Fetching match details for match_id: 6bfa48c9...
Fetching match details for match_id: 7126ce09...
Fetching match details for match_id: 88005716...
Fetching match details for match_id: 4492918b...
Fetching match details for match_id: c2318b28...
Fetching match details for match_id: b52a061a...
Fetching match details for match_id: dde074dc...
Fetching match details for match_id: cdbe786d...
Fetching match details for match_id: cb5cbeee...
Fetching match details for match_id: 3cbdd05f...
Fetching match details for match_id: 39528499...
Fetching match details for match_id: 7bf688a5...
Fetching match details for match_id: ad7ad1ce...
Fetching match details for match_id: 00005440...
Fetching match details for match_id: 48f165d0...
Fetching match details for match_id: dc41788b...
Fetching match details for match_id: 7710524a...
Fetching match details for match_id: 09601c38...
Fetching match details for match_id: 5adf0a01...
Fetching match details for match_id: 732a0dd9...
Fetching match details for match_id: 7a59ef99...
Fetching match details for match_id: fbceff6e...
Fetching match details for match_id: c850930c...
Fetching match details for match_id: dbff25c5...
Fetching match details for match_id: cf381c6d...
Fetching match details for match_id: 4deaa73c...
Fetching match details for match_id: 5e3ddb9c...
Fetching match details for match_id: 8eb0f074...
Fetching match details for match_id: a9335d7e...
Fetching match details for match_id: fae2f1ca...
Fetching match details for match_id: 9fe9433e...
Fetching match details for match_id: b8980cf7...
Fetching match details for match_id: a5d7ac5b...
Fetching match details for match_id: 7412684e...
Fetching match details for match_id: 5ba57b40...
Fetching match details for match_id: 8c5875d0...
Fetching match details for match_id: 4f36a360...
Fetching match details for match_id: 2b04b430...
Fetching match details for match_id: 776d4f68...
Fetching match details for match_id: 628aa734...
Fetching match details for match_id: d2edcbdc...
Fetching match details for match_id: a3e59ea7...
Fetching match details for match_id: 9488560d...
Fetching match details for match_id: 0aca037e...
Fetching match details for match_id: d27ccb63...
Fetching match details for match_id: b82adb59...
Fetching match details for match_id: 6ad9d12e...
Fetching match details for match_id: c0c4c528...
Fetching match details for match_id: f55b349f...
Fetching match details for match_id: b87041dc...
Fetching match details for match_id: c2f3e4cf...
Fetching match details for match_id: de959d20...
Fetching match details for match_id: d3538216...
Fetching match details for match_id: 8f7a2b03...
Fetching match details for match_id: 66830c84...
Fetching match details for match_id: 0dc3b63a...
Fetching match details for match_id: e478c592...
Fetching match details for match_id: fb4a581a...
Fetching match details for match_id: fa87868b...
Fetching match details for match_id: 1e174fdb...
Fetching match details for match_id: dd44a419...
Fetching match details for match_id: 0381b537...
Fetching match details for match_id: 6e8140ed...
Fetching match details for match_id: d543aee8...
Fetching match details for match_id: 6307381b...
Fetching match details for match_id: 783fec34...
Fetching match details for match_id: cc6f63ba...
Fetching match details for match_id: 3474782d...
Fetching match details for match_id: 8b68f347...
Fetching match details for match_id: b07bb9f4...
Fetching match details for match_id: 777c8a22...
Fetching match details for match_id: 4562f3b1...
Fetching match details for match_id: 6a5e75d3...
Fetching match details for match_id: a4209eff...
Fetching match details for match_id: c2c8fd34...
Fetching match details for match_id: 17de87ef...
Fetching match details for match_id: be7adbff...
Fetching match details for match_id: 5b9295ec...
Fetching match details for match_id: 91aa2f0a...
Fetching match details for match_id: 8bb42f9b...
Fetching match details for match_id: 98e7776f...
Fetching match details for match_id: 532dd215...
Fetching match details for match_id: 8fa27714...
Fetching match details for match_id: 5fbe40e9...
Fetching match details for match_id: e6c4ba30...
Fetching match details for match_id: 13c902e2...
Fetching match details for match_id: 8f4c743c...
Fetching match details for match_id: 7a1cc488...
Fetching match details for match_id: e2e56772...
Fetching match details for match_id: 8fdc7a66...
Fetching match details for match_id: 41e5324d...
Fetching match details for match_id: f4397a39...
Fetching match details for match_id: afc6ea35...
Fetching match details for match_id: bb8c4889...
Fetching match details for match_id: de4008a7...
Fetching match details for match_id: 9b31b4df...
Fetching match details for match_id: b6f10939...
Fetching match details for match_id: 3bef3051...
Fetching match details for match_id: 1c672d94...
Fetching match details for match_id: 81ef09ad...
Fetching match details for match_id: 55491f63...
Fetching match details for match_id: 51cce51b...
Fetching match details for match_id: 8923cd55...
Fetching match details for match_id: 1b9b5944...
Fetching match details for match_id: 3fa23c3d...
Fetching match details for match_id: 45c7f322...
Fetching match details for match_id: 741d5ed0...
Fetching match details for match_id: d81d22d2...
Fetching match details for match_id: 760bde3c...
Fetching match details for match_id: c0546323...
Fetching match details for match_id: e0e8dc1b...
Fetching match details for match_id: 2688b507...
Fetching match details for match_id: 935179d4...
Fetching match details for match_id: 7031fa65...
Fetching match details for match_id: f3caf4d1...
Fetching match details for match_id: 8eff1c57...
Fetching match details for match_id: c48d91fc...
Fetching match details for match_id: 30fa0f18...
Fetching match details for match_id: f50ddcdd...
Fetching match details for match_id: 5222ebe1...
Fetching match details for match_id: 60391e88...
Fetching match details for match_id: 9ed541c5...
Fetching match details for match_id: 3693cfdf...
Fetching match details for match_id: d6fcbafa...
Fetching match details for match_id: 80928ead...
Fetching match details for match_id: 862e5b88...
Fetching match details for match_id: 74a49fda...
Fetching match details for match_id: 567d77dd...
Fetching match details for match_id: 5c24a1dd...
Fetching match details for match_id: 8079ea04...
Fetching match details for match_id: f556fdf6...
Fetching match details for match_id: 584f64eb...
Fetching match details for match_id: 77e2a0b1...
Fetching match details for match_id: 08c6d1aa...
Fetching match details for match_id: 88b71553...
Fetching match details for match_id: d14520c7...
Fetching match details for match_id: 0d265aca...
Fetching match details for match_id: 6a36aeb1...
Fetching match details for match_id: 16fb0c16...
Fetching match details for match_id: a9d14e59...
Fetching match details for match_id: c6b3a680...
Fetching match details for match_id: b901c3ad...
Fetching match details for match_id: d8570699...
Fetching match details for match_id: 1945be6e...
Fetching match details for match_id: 95e8d064...
Fetching match details for match_id: aa4c09a1...
Fetching match details for match_id: b6bd1110...
Fetching match details for match_id: dc60c6a9...
Fetching match details for match_id: 55e97718...
Fetching match details for match_id: 19a16e21...
Fetching match details for match_id: e5fa414c...
Fetching match details for match_id: da407af5...
Fetching match details for match_id: 289827b2...
Fetching match details for match_id: 317f5c2b...
Fetching match details for match_id: 5fa2d2fb...
Fetching match details for match_id: 6819c648...
Fetching match details for match_id: 6d5a7570...
Fetching match details for match_id: 94deb265...
Fetching match details for match_id: b9eba194...
Fetching match details for match_id: da63ce9b...
Fetching match details for match_id: f1128312...
Fetching match details for match_id: 3274883b...
Fetching match details for match_id: 0ed26aa5...
Fetching match details for match_id: 7240264e...
Fetching match details for match_id: 2c36c65c...
Fetching match details for match_id: c8dbd2dc...
Fetching match details for match_id: 53c9d299...
Fetching match details for match_id: 1c8ef3fc...
Fetching match details for match_id: a5886923...
Fetching match details for match_id: dc5aa1d2...
Fetching match details for match_id: 6627ebf4...
Fetching match details for match_id: 762e27d7...
Fetching match details for match_id: 2a16ee84...
Fetching match details for match_id: 3bcad21b...
Fetching match details for match_id: 0a00e9c8...
Fetching match details for match_id: 20b2ef17...
Fetching match details for match_id: d6213176...
Fetching match details for match_id: 41562c11...
Fetching match details for match_id: 3d228b41...
Fetching match details for match_id: 464aaada...
Fetching match details for match_id: af7c5c4e...
Fetching match details for match_id: e81ef074...
Fetching match details for match_id: 39d008a9...
Fetching match details for match_id: 715afa91...
Fetching match details for match_id: ad8a0484...
Fetching match details for match_id: a899b0b1...
Fetching match details for match_id: faa9e528...
Fetching match details for match_id: 3d09eb6c...
Fetching match details for match_id: 1fe2a048...
Fetching match details for match_id: 1f72d392...
Fetching match details for match_id: 0641a6bf...
Fetching match details for match_id: 6f9707ed...
Fetching match details for match_id: d09f754b...
Fetching match details for match_id: 9203ce59...
Fetching match details for match_id: afd1f312...
Fetching match details for match_id: 825da9e7...
Fetching match details for match_id: 66afaec2...
Fetching match details for match_id: c367c9bb...
Fetching match details for match_id: 337dd942...
Fetching match details for match_id: c09a6180...
Fetching match details for match_id: a215a140...
Fetching match details for match_id: e1440199...
Fetching match details for match_id: 7c94492d...

In [56]:
matches

,match_id,date,kickoff_time,season,competition_id,competition,venue_id,venue,city_played,home_team,...,away_team_id,home_score,away_score,completed,is_tournament,played_on_grass,attendance,home_team_form,away_team_form,referee
0,26eb0d57,20220205,NaN,2022,7a1361e7,Six Nations,07b0586c,Aviva Stadium,Dublin,Ireland,...,094dae60,29,7,True,1.0,1.0,None,LWWLW,LLWLW,None
0,d803469c,20220205,NaN,2022,7a1361e7,Six Nations,a35811c5,Scottish Gas Murrayfield,Edinburgh,Scotland,...,f60f757d,20,17,True,1.0,1.0,None,WLLWW,WWWWW,None
0,4a49c716,20220206,NaN,2022,7a1361e7,Six Nations,5b691aae,Stade de France,Saint-Denis,France,...,d0cffe5e,37,10,True,1.0,1.0,None,WWLLL,WLWLL,None
0,7ec3e5e5,20220212,NaN,2022,7a1361e7,Six Nations,fe933f9f,Principality Stadium,Cardiff,Wales,...,4409215c,20,17,True,1.0,1.0,None,LLWLW,WLLWW,None
0,71ccf2fb,20220212,NaN,2022,7a1361e7,Six Nations,5b691aae,Stade de France,Saint-Denis,France,...,165b36e5,30,24,True,1.0,1.0,None,WWLLL,LWWLW,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,337dd942,20260808,08:10,2026,96c775f2,International Test Match,b9cf87a3,Estadio José Amalfitani,Buenos Aires,Argentina,...,9b93d911,10,17,True,False,True,None,LLLWL,WLWWW,None
0,c09a6180,20260815,08:10,2026,96c775f2,International Test Match,eb9c53f6,Queensland Country Bank Stadium,Townsville,Australia,...,f97333f3,56,17,True,False,True,None,WWWWL,LLLLW,None
0,a215a140,20260822,08:10,2026,96c775f2,International Test Match,e952f544,Ellis Park,Johannesburg,South Africa,...,d75e45cc,16,33,True,False,True,None,WLWWW,LWWWW,None
0,e1440199,20260829,08:10,2026,96c775f2,International Test Match,3ce3079c,DHL Stadium,Cape Town,South Africa,...,d75e45cc,33,26,True,False,True,None,WLWWW,LWWWW,None
0,7c94492d,20260829,08:10,2026,96c775f2,International Test Match,2b186ab0,Estadio 23 de Agosto,San Salvador,Argentina,...,b904fef9,21,27,True,False,True,None,LLLWL,WWWWL,None